/*
	CSCArrayOfHealthBeneficiary.h
	The interface definition of properties and methods for the CSCArrayOfHealthBeneficiary array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCHealthBeneficiary;
@interface CSCArrayOfHealthBeneficiary : SoapArray
{
}

@end
