/*
	CSCArrayOfSavingsScheme.h
	The interface definition of properties and methods for the CSCArrayOfSavingsScheme array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCSavingsScheme;
@interface CSCArrayOfSavingsScheme : SoapArray
{
}

@end
