/*
	CSCArrayOfString.h
	The implementation of properties and methods for the CSCArrayOfString array.
	Generated by SudzC.com
*/
#import "CSCArrayOfString.h"

@implementation CSCArrayOfString

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfString alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				NSString* value = [child stringValue];
				[self addObject: value];
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [[item stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		}
		return s;
	}
@end
