/*
	CSCArrayOfOperationAllocation.h
	The interface definition of properties and methods for the CSCArrayOfOperationAllocation array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCOperationAllocation;
@interface CSCArrayOfOperationAllocation : SoapArray
{
}

@end
