/*
	CSCArrayOfOrganizationDetail.h
	The implementation of properties and methods for the CSCArrayOfOrganizationDetail array.
	Generated by SudzC.com
*/
#import "CSCArrayOfOrganizationDetail.h"

#import "CSCOrganizationDetail.h"
@implementation CSCArrayOfOrganizationDetail

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfOrganizationDetail alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCOrganizationDetail* value = [[CSCOrganizationDetail createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"OrganizationDetail"]];
		}
		return s;
	}
@end
