/*
	CSCArrayOfHouseholdTax.h
	The interface definition of properties and methods for the CSCArrayOfHouseholdTax array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCHouseholdTax;
@interface CSCArrayOfHouseholdTax : SoapArray
{
}

@end
