/*
	CSCArrayOfTax.h
	The implementation of properties and methods for the CSCArrayOfTax array.
	Generated by SudzC.com
*/
#import "CSCArrayOfTax.h"

#import "CSCTax.h"
@implementation CSCArrayOfTax

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfTax alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCTax* value = [[CSCTax createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Tax"]];
		}
		return s;
	}
@end
