/*
	CSCArrayOfClause.h
	The interface definition of properties and methods for the CSCArrayOfClause array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCClause;
@interface CSCArrayOfClause : SoapArray
{
}

@end
