/*
	CSCArrayOfPackage.h
	The interface definition of properties and methods for the CSCArrayOfPackage array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCPackage;
@interface CSCArrayOfPackage : SoapArray
{
}

@end
