/*
	CSCArrayOfNetworkMembership.h
	The implementation of properties and methods for the CSCArrayOfNetworkMembership array.
	Generated by SudzC.com
*/
#import "CSCArrayOfNetworkMembership.h"

#import "CSCNetworkMembership.h"
@implementation CSCArrayOfNetworkMembership

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfNetworkMembership alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCNetworkMembership* value = [[CSCNetworkMembership createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"NetworkMembership"]];
		}
		return s;
	}
@end
