/*
	CSCArrayOfPostalAddress.h
	The interface definition of properties and methods for the CSCArrayOfPostalAddress array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCPostalAddress;
@interface CSCArrayOfPostalAddress : SoapArray
{
}

@end
