/*
	CSCArrayOfInsuredGroup.h
	The interface definition of properties and methods for the CSCArrayOfInsuredGroup array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCInsuredGroup;
@interface CSCArrayOfInsuredGroup : SoapArray
{
}

@end
