/*
	CSCArrayOfSettlementItem.h
	The implementation of properties and methods for the CSCArrayOfSettlementItem array.
	Generated by SudzC.com
*/
#import "CSCArrayOfSettlementItem.h"

#import "CSCSettlementItem.h"
@implementation CSCArrayOfSettlementItem

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfSettlementItem alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCSettlementItem* value = [[CSCSettlementItem createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"SettlementItem"]];
		}
		return s;
	}
@end
