/*
	CSCArrayOfSavingsProfile.h
	The implementation of properties and methods for the CSCArrayOfSavingsProfile array.
	Generated by SudzC.com
*/
#import "CSCArrayOfSavingsProfile.h"

#import "CSCSavingsProfile.h"
@implementation CSCArrayOfSavingsProfile

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfSavingsProfile alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCSavingsProfile* value = [[CSCSavingsProfile createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"SavingsProfile"]];
		}
		return s;
	}
@end
