/*
	CSCArrayOfExtensionElement.h
	The implementation of properties and methods for the CSCArrayOfExtensionElement array.
	Generated by SudzC.com
*/
#import "CSCArrayOfExtensionElement.h"

#import "CSCExtensionElement.h"
@implementation CSCArrayOfExtensionElement

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfExtensionElement alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCExtensionElement* value = [[CSCExtensionElement createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"ExtensionElement"]];
		}
		return s;
	}
@end
