/*
	CSCArrayOfBeneficiary.h
	The implementation of properties and methods for the CSCArrayOfBeneficiary array.
	Generated by SudzC.com
*/
#import "CSCArrayOfBeneficiary.h"

#import "CSCBeneficiary.h"
@implementation CSCArrayOfBeneficiary

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfBeneficiary alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCBeneficiary* value = [[CSCBeneficiary createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Beneficiary"]];
		}
		return s;
	}
@end
