/*
	CSCArrayOfEMailAddress.h
	The interface definition of properties and methods for the CSCArrayOfEMailAddress array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCEMailAddress;
@interface CSCArrayOfEMailAddress : SoapArray
{
}

@end
