/*
	CSCArrayOfEmployeeGroup.h
	The implementation of properties and methods for the CSCArrayOfEmployeeGroup array.
	Generated by SudzC.com
*/
#import "CSCArrayOfEmployeeGroup.h"

#import "CSCEmployeeGroup.h"
@implementation CSCArrayOfEmployeeGroup

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfEmployeeGroup alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCEmployeeGroup* value = [[CSCEmployeeGroup createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"EmployeeGroup"]];
		}
		return s;
	}
@end
