/*
	CSCArrayOfExtraPremiumDetail.h
	The interface definition of properties and methods for the CSCArrayOfExtraPremiumDetail array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCExtraPremiumDetail;
@interface CSCArrayOfExtraPremiumDetail : SoapArray
{
}

@end
