/*
	CSCArrayOfGeneralConditions.h
	The interface definition of properties and methods for the CSCArrayOfGeneralConditions array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCGeneralConditions;
@interface CSCArrayOfGeneralConditions : SoapArray
{
}

@end
