/*
	CSCArrayOfOperation.h
	The implementation of properties and methods for the CSCArrayOfOperation array.
	Generated by SudzC.com
*/
#import "CSCArrayOfOperation.h"

#import "CSCOperation.h"
@implementation CSCArrayOfOperation

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfOperation alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCOperation* value = [[CSCOperation createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Operation"]];
		}
		return s;
	}
@end
