/*
	CSCArrayOfUnitLinkedFundItem.h
	The interface definition of properties and methods for the CSCArrayOfUnitLinkedFundItem array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCUnitLinkedFundItem;
@interface CSCArrayOfUnitLinkedFundItem : SoapArray
{
}

@end
