/*
	CSCArrayOfHealthFormula.h
	The interface definition of properties and methods for the CSCArrayOfHealthFormula array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCHealthFormula;
@interface CSCArrayOfHealthFormula : SoapArray
{
}

@end
