/*
	CSCArrayOfSettlementBeneficiary.h
	The interface definition of properties and methods for the CSCArrayOfSettlementBeneficiary array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCSettlementBeneficiary;
@interface CSCArrayOfSettlementBeneficiary : SoapArray
{
}

@end
