/*
	CSCArrayOfPartyRelationship.h
	The implementation of properties and methods for the CSCArrayOfPartyRelationship array.
	Generated by SudzC.com
*/
#import "CSCArrayOfPartyRelationship.h"

#import "CSCPartyRelationship.h"
@implementation CSCArrayOfPartyRelationship

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfPartyRelationship alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCPartyRelationship* value = [[CSCPartyRelationship createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"PartyRelationship"]];
		}
		return s;
	}
@end
