/*
	CSCArrayOfDeathTax.h
	The implementation of properties and methods for the CSCArrayOfDeathTax array.
	Generated by SudzC.com
*/
#import "CSCArrayOfDeathTax.h"

#import "CSCDeathTax.h"
@implementation CSCArrayOfDeathTax

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfDeathTax alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCDeathTax* value = [[CSCDeathTax createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"DeathTax"]];
		}
		return s;
	}
@end
