/*
	CSCArrayOfHealthCondition.h
	The interface definition of properties and methods for the CSCArrayOfHealthCondition array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCHealthCondition;
@interface CSCArrayOfHealthCondition : SoapArray
{
}

@end
