/*
	CSCArrayOfLoan.h
	The implementation of properties and methods for the CSCArrayOfLoan array.
	Generated by SudzC.com
*/
#import "CSCArrayOfLoan.h"

#import "CSCLoan.h"
@implementation CSCArrayOfLoan

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfLoan alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCLoan* value = [[CSCLoan createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Loan"]];
		}
		return s;
	}
@end
