/*
	CSCArrayOfDisbursementSplit.h
	The interface definition of properties and methods for the CSCArrayOfDisbursementSplit array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCDisbursementSplit;
@interface CSCArrayOfDisbursementSplit : SoapArray
{
}

@end
