/*
	CSCArrayOfQuestionAnswer.h
	The interface definition of properties and methods for the CSCArrayOfQuestionAnswer array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCQuestionAnswer;
@interface CSCArrayOfQuestionAnswer : SoapArray
{
}

@end
