/*
	CSCArrayOfHealthFormulaItem.h
	The implementation of properties and methods for the CSCArrayOfHealthFormulaItem array.
	Generated by SudzC.com
*/
#import "CSCArrayOfHealthFormulaItem.h"

#import "CSCHealthFormulaItem.h"
@implementation CSCArrayOfHealthFormulaItem

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfHealthFormulaItem alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCHealthFormulaItem* value = [[CSCHealthFormulaItem createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"HealthFormulaItem"]];
		}
		return s;
	}
@end
