/*
	CSCArrayOfAdditionalClauseDetail.h
	The interface definition of properties and methods for the CSCArrayOfAdditionalClauseDetail array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCAdditionalClauseDetail;
@interface CSCArrayOfAdditionalClauseDetail : SoapArray
{
}

@end
