/*
	CSCArrayOfCoverage.h
	The interface definition of properties and methods for the CSCArrayOfCoverage array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCCoverage;
@interface CSCArrayOfCoverage : SoapArray
{
}

@end
