/*
	CSCArrayOfInjuryCompensation.h
	The interface definition of properties and methods for the CSCArrayOfInjuryCompensation array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCInjuryCompensation;
@interface CSCArrayOfInjuryCompensation : SoapArray
{
}

@end
