/*
	CSCArrayOfString.h
	The interface definition of properties and methods for the CSCArrayOfString array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@interface CSCArrayOfString : SoapArray
{
}

@end
