/*
	CSCArrayOfHouseholdTax.h
	The implementation of properties and methods for the CSCArrayOfHouseholdTax array.
	Generated by SudzC.com
*/
#import "CSCArrayOfHouseholdTax.h"

#import "CSCHouseholdTax.h"
@implementation CSCArrayOfHouseholdTax

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfHouseholdTax alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCHouseholdTax* value = [[CSCHouseholdTax createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"HouseholdTax"]];
		}
		return s;
	}
@end
