/*
	CSCArrayOfSettlement.h
	The interface definition of properties and methods for the CSCArrayOfSettlement array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCSettlement;
@interface CSCArrayOfSettlement : SoapArray
{
}

@end
