/*
	CSCArrayOfSavingsFlow.h
	The interface definition of properties and methods for the CSCArrayOfSavingsFlow array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCSavingsFlow;
@interface CSCArrayOfSavingsFlow : SoapArray
{
}

@end
