/*
	CSCArrayOfPhoneAddress.h
	The implementation of properties and methods for the CSCArrayOfPhoneAddress array.
	Generated by SudzC.com
*/
#import "CSCArrayOfPhoneAddress.h"

#import "CSCPhoneAddress.h"
@implementation CSCArrayOfPhoneAddress

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfPhoneAddress alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCPhoneAddress* value = [[CSCPhoneAddress createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"PhoneAddress"]];
		}
		return s;
	}
@end
