/*
	CSCArrayOfLesion.h
	The interface definition of properties and methods for the CSCArrayOfLesion array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCLesion;
@interface CSCArrayOfLesion : SoapArray
{
}

@end
