/*
	CSCArrayOfPayPoint.h
	The implementation of properties and methods for the CSCArrayOfPayPoint array.
	Generated by SudzC.com
*/
#import "CSCArrayOfPayPoint.h"

#import "CSCPayPoint.h"
@implementation CSCArrayOfPayPoint

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfPayPoint alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCPayPoint* value = [[CSCPayPoint createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"PayPoint"]];
		}
		return s;
	}
@end
