/*
	CSCArrayOfMemberSituation.h
	The implementation of properties and methods for the CSCArrayOfMemberSituation array.
	Generated by SudzC.com
*/
#import "CSCArrayOfMemberSituation.h"

#import "CSCMemberSituation.h"
@implementation CSCArrayOfMemberSituation

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfMemberSituation alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCMemberSituation* value = [[CSCMemberSituation createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"MemberSituation"]];
		}
		return s;
	}
@end
