/*
	CSCArrayOfDate.h
	The implementation of properties and methods for the CSCArrayOfDate array.
	Generated by SudzC.com
*/
#import "CSCArrayOfDate.h"

@implementation CSCArrayOfDate

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfDate alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				NSDate* value = [Soap dateFromString: [child stringValue]];
				[self addObject: value];
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [Soap getDateString: item]];
		}
		return s;
	}
@end
