/*
	CSCArrayOfHealthAllocation.h
	The implementation of properties and methods for the CSCArrayOfHealthAllocation array.
	Generated by SudzC.com
*/
#import "CSCArrayOfHealthAllocation.h"

#import "CSCHealthAllocation.h"
@implementation CSCArrayOfHealthAllocation

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfHealthAllocation alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCHealthAllocation* value = [[CSCHealthAllocation createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"HealthAllocation"]];
		}
		return s;
	}
@end
