/*
	CSCArrayOfFundsAllocation.h
	The interface definition of properties and methods for the CSCArrayOfFundsAllocation array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCFundsAllocation;
@interface CSCArrayOfFundsAllocation : SoapArray
{
}

@end
