/*
	CSCArrayOfRegistration.h
	The interface definition of properties and methods for the CSCArrayOfRegistration array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCRegistration;
@interface CSCArrayOfRegistration : SoapArray
{
}

@end
