/*
	CSCArrayOfHealthConditionalLimit.h
	The interface definition of properties and methods for the CSCArrayOfHealthConditionalLimit array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCHealthConditionalLimit;
@interface CSCArrayOfHealthConditionalLimit : SoapArray
{
}

@end
