/*
	CSCArrayOfProductOption.h
	The interface definition of properties and methods for the CSCArrayOfProductOption array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCProductOption;
@interface CSCArrayOfProductOption : SoapArray
{
}

@end
