/*
	CSCArrayOfPayPoint.h
	The interface definition of properties and methods for the CSCArrayOfPayPoint array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCPayPoint;
@interface CSCArrayOfPayPoint : SoapArray
{
}

@end
