/*
	CSCArrayOfFinancialActivity.h
	The implementation of properties and methods for the CSCArrayOfFinancialActivity array.
	Generated by SudzC.com
*/
#import "CSCArrayOfFinancialActivity.h"

#import "CSCFinancialActivity.h"
@implementation CSCArrayOfFinancialActivity

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfFinancialActivity alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCFinancialActivity* value = [[CSCFinancialActivity createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"FinancialActivity"]];
		}
		return s;
	}
@end
