/*
	CSCArrayOfMedicalTreatment.h
	The interface definition of properties and methods for the CSCArrayOfMedicalTreatment array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCMedicalTreatment;
@interface CSCArrayOfMedicalTreatment : SoapArray
{
}

@end
