/*
	CSCArrayOfInterestFundItem.h
	The implementation of properties and methods for the CSCArrayOfInterestFundItem array.
	Generated by SudzC.com
*/
#import "CSCArrayOfInterestFundItem.h"

#import "CSCInterestFundItem.h"
@implementation CSCArrayOfInterestFundItem

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfInterestFundItem alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCInterestFundItem* value = [[CSCInterestFundItem createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"InterestFundItem"]];
		}
		return s;
	}
@end
