/*
	CSCArrayOfSettlementBeneficiary.h
	The implementation of properties and methods for the CSCArrayOfSettlementBeneficiary array.
	Generated by SudzC.com
*/
#import "CSCArrayOfSettlementBeneficiary.h"

#import "CSCSettlementBeneficiary.h"
@implementation CSCArrayOfSettlementBeneficiary

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfSettlementBeneficiary alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCSettlementBeneficiary* value = [[CSCSettlementBeneficiary createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"SettlementBeneficiary"]];
		}
		return s;
	}
@end
