/*
	CSCArrayOfSavingsFlow.h
	The implementation of properties and methods for the CSCArrayOfSavingsFlow array.
	Generated by SudzC.com
*/
#import "CSCArrayOfSavingsFlow.h"

#import "CSCSavingsFlow.h"
@implementation CSCArrayOfSavingsFlow

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfSavingsFlow alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCSavingsFlow* value = [[CSCSavingsFlow createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"SavingsFlow"]];
		}
		return s;
	}
@end
