/*
	CSCArrayOfDamage.h
	The interface definition of properties and methods for the CSCArrayOfDamage array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCDamage;
@interface CSCArrayOfDamage : SoapArray
{
}

@end
