/*
	CSCArrayOfInterestFundItem.h
	The interface definition of properties and methods for the CSCArrayOfInterestFundItem array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCInterestFundItem;
@interface CSCArrayOfInterestFundItem : SoapArray
{
}

@end
