/*
	CSCArrayOfBankAccount.h
	The interface definition of properties and methods for the CSCArrayOfBankAccount array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCBankAccount;
@interface CSCArrayOfBankAccount : SoapArray
{
}

@end
