/*
	CSCArrayOfPenaltyRate.h
	The implementation of properties and methods for the CSCArrayOfPenaltyRate array.
	Generated by SudzC.com
*/
#import "CSCArrayOfPenaltyRate.h"

#import "CSCPenaltyRate.h"
@implementation CSCArrayOfPenaltyRate

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[CSCArrayOfPenaltyRate alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				CSCPenaltyRate* value = [[CSCPenaltyRate createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"PenaltyRate"]];
		}
		return s;
	}
@end
