/*
	CSCBuildingLoss.h
	The implementation of properties and methods for the CSCBuildingLoss object.
	Generated by SudzC.com
*/
#import "CSCBuildingLoss.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
@implementation CSCBuildingLoss
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize AbsenceEndDate = _AbsenceEndDate;
	@synthesize AbsenceStartDate = _AbsenceStartDate;
	@synthesize BuildingStatementDate = _BuildingStatementDate;
	@synthesize NeighbourhoodDamage = _NeighbourhoodDamage;
	@synthesize Origin = _Origin;
	@synthesize WaterTurnedOff = _WaterTurnedOff;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.AbsenceEndDate = nil;
			self.AbsenceStartDate = nil;
			self.BuildingStatementDate = nil;
			self.Origin = nil;

		}
		return self;
	}

	+ (CSCBuildingLoss*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCBuildingLoss*)[[CSCBuildingLoss alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.AbsenceEndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"AbsenceEndDate"]];
			self.AbsenceStartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"AbsenceStartDate"]];
			self.BuildingStatementDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"BuildingStatementDate"]];
			self.NeighbourhoodDamage = [[Soap getNodeValue: node withName: @"NeighbourhoodDamage"] boolValue];
			self.Origin = [Soap getNodeValue: node withName: @"Origin"];
			self.WaterTurnedOff = [[Soap getNodeValue: node withName: @"WaterTurnedOff"] boolValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"BuildingLoss"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.AbsenceEndDate != nil) [s appendFormat: @"<AbsenceEndDate>%@</AbsenceEndDate>", [Soap getDateString: self.AbsenceEndDate]];
		if (self.AbsenceStartDate != nil) [s appendFormat: @"<AbsenceStartDate>%@</AbsenceStartDate>", [Soap getDateString: self.AbsenceStartDate]];
		if (self.BuildingStatementDate != nil) [s appendFormat: @"<BuildingStatementDate>%@</BuildingStatementDate>", [Soap getDateString: self.BuildingStatementDate]];
		[s appendFormat: @"<NeighbourhoodDamage>%@</NeighbourhoodDamage>", (self.NeighbourhoodDamage)?@"true":@"false"];
		if (self.Origin != nil) [s appendFormat: @"<Origin>%@</Origin>", [[self.Origin stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		[s appendFormat: @"<WaterTurnedOff>%@</WaterTurnedOff>", (self.WaterTurnedOff)?@"true":@"false"];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCBuildingLoss class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
