/*
	CSCBuilding.h
	The implementation of properties and methods for the CSCBuilding object.
	Generated by SudzC.com
*/
#import "CSCBuilding.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCPostalAddress.h"
@implementation CSCBuilding
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize PostalAddress = _PostalAddress;
	@synthesize SumInsured = _SumInsured;
	@synthesize SumInsuredValuation = _SumInsuredValuation;
	@synthesize SumInsuredValuationLabel = _SumInsuredValuationLabel;
	@synthesize ConstructionYear = _ConstructionYear;
	@synthesize Floors = _Floors;
	@synthesize InsuredFurnitureAmount = _InsuredFurnitureAmount;
	@synthesize LandParcel = _LandParcel;
	@synthesize LandRegistry = _LandRegistry;
	@synthesize SurfaceArea = _SurfaceArea;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.PostalAddress = nil; // [[CSCPostalAddress alloc] init];
			self.SumInsured = nil;
			self.SumInsuredValuation = nil;
			self.SumInsuredValuationLabel = nil;
			self.InsuredFurnitureAmount = nil;
			self.LandParcel = nil;
			self.LandRegistry = nil;
			self.SurfaceArea = nil;

		}
		return self;
	}

	+ (CSCBuilding*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCBuilding*)[[CSCBuilding alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.PostalAddress = [[CSCPostalAddress createWithNode: [Soap getNode: node withName: @"PostalAddress"]] object];
			self.SumInsured = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"SumInsured"]];
			self.SumInsuredValuation = [Soap getNodeValue: node withName: @"SumInsuredValuation"];
			self.SumInsuredValuationLabel = [Soap getNodeValue: node withName: @"SumInsuredValuationLabel"];
			self.ConstructionYear = [[Soap getNodeValue: node withName: @"ConstructionYear"] intValue];
			self.Floors = [[Soap getNodeValue: node withName: @"Floors"] intValue];
			self.InsuredFurnitureAmount = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"InsuredFurnitureAmount"]];
			self.LandParcel = [Soap getNodeValue: node withName: @"LandParcel"];
			self.LandRegistry = [Soap getNodeValue: node withName: @"LandRegistry"];
			self.SurfaceArea = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"SurfaceArea"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Building"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.PostalAddress != nil) [s appendString: [self.PostalAddress serialize: @"PostalAddress"]];
		if (self.SumInsured != nil) [s appendFormat: @"<SumInsured>%@</SumInsured>", [NSString stringWithFormat: @"%@", self.SumInsured]];
		if (self.SumInsuredValuation != nil) [s appendFormat: @"<SumInsuredValuation>%@</SumInsuredValuation>", [[self.SumInsuredValuation stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.SumInsuredValuationLabel != nil) [s appendFormat: @"<SumInsuredValuationLabel>%@</SumInsuredValuationLabel>", [[self.SumInsuredValuationLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		[s appendFormat: @"<ConstructionYear>%@</ConstructionYear>", [NSString stringWithFormat: @"%i", self.ConstructionYear]];
		[s appendFormat: @"<Floors>%@</Floors>", [NSString stringWithFormat: @"%i", self.Floors]];
		if (self.InsuredFurnitureAmount != nil) [s appendFormat: @"<InsuredFurnitureAmount>%@</InsuredFurnitureAmount>", [NSString stringWithFormat: @"%@", self.InsuredFurnitureAmount]];
		if (self.LandParcel != nil) [s appendFormat: @"<LandParcel>%@</LandParcel>", [[self.LandParcel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.LandRegistry != nil) [s appendFormat: @"<LandRegistry>%@</LandRegistry>", [[self.LandRegistry stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.SurfaceArea != nil) [s appendFormat: @"<SurfaceArea>%@</SurfaceArea>", [NSString stringWithFormat: @"%@", self.SurfaceArea]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCBuilding class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
