/*
	CSCBuildingLoss.h
	The interface definition of properties and methods for the CSCBuildingLoss object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCBuildingLoss : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _AbsenceEndDate;
	NSDate* _AbsenceStartDate;
	NSDate* _BuildingStatementDate;
	BOOL _NeighbourhoodDamage;
	NSString* _Origin;
	BOOL _WaterTurnedOff;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* AbsenceEndDate;
	@property (strong, nonatomic) NSDate* AbsenceStartDate;
	@property (strong, nonatomic) NSDate* BuildingStatementDate;
	@property BOOL NeighbourhoodDamage;
	@property (strong, nonatomic) NSString* Origin;
	@property BOOL WaterTurnedOff;

	+ (CSCBuildingLoss*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
