/*
	CSCBilling.h
	The interface definition of properties and methods for the CSCBilling object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCBankAccount;
@class CSCContract;
@class CSCCreditCard;
@class CSCArrayOfString;
@class CSCDirectDebitMandate;
@class CSCEmployeeGroup;
@class CSCArrayOfFeesOverride;
@class CSCArrayOfString;
@class CSCArrayOfString;
@class CSCArrayOfFundsAllocation;
@class CSCIndexation;
@class CSCPayPoint;
@class CSCPartyRole;
@class CSCArrayOfPartyRole;
#import "CSCObject.h"
@class CSCObject;


@interface CSCBilling : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSDecimalNumber* _Amount;
	CSCBankAccount* _BankAccount;
	NSString* _BillReceiver;
	NSString* _BillReceiverLabel;
	CSCContract* _Contract;
	CSCCreditCard* _CreditCard;
	NSString* _CurrencyCode;
	NSString* _DirectDebitDay;
	NSMutableArray* _DirectDebitDayList;
	CSCDirectDebitMandate* _DirectDebitMandate;
	NSString* _DirectDebitStatus;
	NSString* _DueDateType;
	NSString* _DueDateTypeLabel;
	CSCEmployeeGroup* _EmployeeGroup;
	NSMutableArray* _FeesOverrideList;
	NSString* _Frequency;
	NSDecimalNumber* _FrequencyFees;
	NSString* _FrequencyLabel;
	NSMutableArray* _FrequencyLabelList;
	NSMutableArray* _FrequencyList;
	NSString* _FrequencyType;
	NSMutableArray* _FundsAllocationList;
	CSCIndexation* _Indexation;
	BOOL _IndexationEnabled;
	NSDecimalNumber* _InitialPremiumAmount;
	int _InitialPremiumNumber;
	int _MainDueDay;
	int _MainDueMonth;
	NSString* _MarketingCode;
	NSDate* _NextDueDate;
	CSCPayPoint* _PayPoint;
	CSCPartyRole* _Payer;
	NSString* _PaymentSource;
	NSString* _PaymentType;
	NSString* _PaymentTypeLabel;
	NSDate* _RestartDate;
	NSMutableArray* _RoleList;
	NSDate* _SignatureDate;
	NSString* _Status;
	NSDate* _StopDate;
	NSString* _StopMotive;
	BOOL _TaxIncludedAmount;
	NSString* _TaxRule;
	NSDecimalNumber* _Threshold;
	NSString* _Type;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSDecimalNumber* Amount;
	@property (strong, nonatomic) CSCBankAccount* BankAccount;
	@property (strong, nonatomic) NSString* BillReceiver;
	@property (strong, nonatomic) NSString* BillReceiverLabel;
	@property (strong, nonatomic) CSCContract* Contract;
	@property (strong, nonatomic) CSCCreditCard* CreditCard;
	@property (strong, nonatomic) NSString* CurrencyCode;
	@property (strong, nonatomic) NSString* DirectDebitDay;
	@property (strong, nonatomic) NSMutableArray* DirectDebitDayList;
	@property (strong, nonatomic) CSCDirectDebitMandate* DirectDebitMandate;
	@property (strong, nonatomic) NSString* DirectDebitStatus;
	@property (strong, nonatomic) NSString* DueDateType;
	@property (strong, nonatomic) NSString* DueDateTypeLabel;
	@property (strong, nonatomic) CSCEmployeeGroup* EmployeeGroup;
	@property (strong, nonatomic) NSMutableArray* FeesOverrideList;
	@property (strong, nonatomic) NSString* Frequency;
	@property (strong, nonatomic) NSDecimalNumber* FrequencyFees;
	@property (strong, nonatomic) NSString* FrequencyLabel;
	@property (strong, nonatomic) NSMutableArray* FrequencyLabelList;
	@property (strong, nonatomic) NSMutableArray* FrequencyList;
	@property (strong, nonatomic) NSString* FrequencyType;
	@property (strong, nonatomic) NSMutableArray* FundsAllocationList;
	@property (strong, nonatomic) CSCIndexation* Indexation;
	@property BOOL IndexationEnabled;
	@property (strong, nonatomic) NSDecimalNumber* InitialPremiumAmount;
	@property int InitialPremiumNumber;
	@property int MainDueDay;
	@property int MainDueMonth;
	@property (strong, nonatomic) NSString* MarketingCode;
	@property (strong, nonatomic) NSDate* NextDueDate;
	@property (strong, nonatomic) CSCPayPoint* PayPoint;
	@property (strong, nonatomic) CSCPartyRole* Payer;
	@property (strong, nonatomic) NSString* PaymentSource;
	@property (strong, nonatomic) NSString* PaymentType;
	@property (strong, nonatomic) NSString* PaymentTypeLabel;
	@property (strong, nonatomic) NSDate* RestartDate;
	@property (strong, nonatomic) NSMutableArray* RoleList;
	@property (strong, nonatomic) NSDate* SignatureDate;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSDate* StopDate;
	@property (strong, nonatomic) NSString* StopMotive;
	@property BOOL TaxIncludedAmount;
	@property (strong, nonatomic) NSString* TaxRule;
	@property (strong, nonatomic) NSDecimalNumber* Threshold;
	@property (strong, nonatomic) NSString* Type;

	+ (CSCBilling*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
