/*
	CSCClaimFolder.h
	The interface definition of properties and methods for the CSCClaimFolder object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCClaimDeathTax;
@class CSCClaimEvent;
@class CSCClaimParty;
@class CSCClaimReserve;
@class CSCClaimReserve;
@class CSCArrayOfSettlementFolder;
#import "CSCObject.h"
@class CSCObject;


@interface CSCClaimFolder : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSDate* _AcceptanceDate;
	CSCClaimDeathTax* _ClaimDeathTax;
	CSCClaimEvent* _ClaimEvent;
	CSCClaimParty* _ClaimParty;
	NSDecimalNumber* _CompensationReserve;
	NSString* _ContractNumber;
	NSDecimalNumber* _FeesReserve;
	NSString* _Identifier;
	NSString* _ProductIdentifier;
	NSString* _ProductLabel;
	CSCClaimReserve* _Provision;
	CSCClaimReserve* _Recourse;
	NSDate* _SearchCoverageDate;
	NSMutableArray* _SettlementFolderList;
	NSString* _Status;
	NSDate* _StatusDate;
	NSString* _StatusLabel;
	NSString* _StatusMotive;
	NSString* _StatusMotiveLabel;
	NSDecimalNumber* _TotalAmount;
	NSDecimalNumber* _TotalAmount2;
	NSDecimalNumber* _TotalRecoveryAmount;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSDate* AcceptanceDate;
	@property (strong, nonatomic) CSCClaimDeathTax* ClaimDeathTax;
	@property (strong, nonatomic) CSCClaimEvent* ClaimEvent;
	@property (strong, nonatomic) CSCClaimParty* ClaimParty;
	@property (strong, nonatomic) NSDecimalNumber* CompensationReserve;
	@property (strong, nonatomic) NSString* ContractNumber;
	@property (strong, nonatomic) NSDecimalNumber* FeesReserve;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) NSString* ProductIdentifier;
	@property (strong, nonatomic) NSString* ProductLabel;
	@property (strong, nonatomic) CSCClaimReserve* Provision;
	@property (strong, nonatomic) CSCClaimReserve* Recourse;
	@property (strong, nonatomic) NSDate* SearchCoverageDate;
	@property (strong, nonatomic) NSMutableArray* SettlementFolderList;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSDate* StatusDate;
	@property (strong, nonatomic) NSString* StatusLabel;
	@property (strong, nonatomic) NSString* StatusMotive;
	@property (strong, nonatomic) NSString* StatusMotiveLabel;
	@property (strong, nonatomic) NSDecimalNumber* TotalAmount;
	@property (strong, nonatomic) NSDecimalNumber* TotalAmount2;
	@property (strong, nonatomic) NSDecimalNumber* TotalRecoveryAmount;

	+ (CSCClaimFolder*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
