/*
	CSCClaimEvent.h
	The interface definition of properties and methods for the CSCClaimEvent object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCClaimCause;
@class CSCArrayOfClaimFolder;
@class CSCArrayOfClaimParty;
@class CSCInsuredRisk;
@class CSCPostalAddress;
@class CSCLoss;
@class CSCArrayOfOperation;
@class CSCPerson;
@class CSCArrayOfClaimEventPeriod;
@class CSCArrayOfRelatedFolder;
@class CSCArrayOfString;
@class CSCArrayOfPartyRole;
@class CSCArrayOfSettlementTax;
#import "CSCObject.h"
@class CSCObject;


@interface CSCClaimEvent : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSDate* _AcceptanceDate;
	NSString* _CircumstanceCode;
	NSString* _CircumstanceLabel;
	CSCClaimCause* _ClaimCause;
	NSMutableArray* _ClaimFolderList;
	NSMutableArray* _ClaimPartyList;
	NSDate* _Date;
	NSString* _Identifier;
	CSCInsuredRisk* _InsuredRisk;
	NSDate* _LearnedAboutDate;
	NSString* _Liability;
	NSString* _Location;
	CSCPostalAddress* _LocationAddress;
	CSCLoss* _Loss;
	NSDate* _NotificationDate;
	NSMutableArray* _OperationList;
	CSCPerson* _Owner;
	NSMutableArray* _PeriodList;
	NSString* _PlaceCode;
	NSString* _PlaceLabel;
	int _RejectCount;
	NSMutableArray* _RelatedFolderList;
	NSMutableArray* _Remark;
	NSMutableArray* _RoleList;
	NSString* _Status;
	NSDate* _StatusDate;
	NSString* _StatusLabel;
	NSString* _StatusMotive;
	NSString* _StatusMotiveLabel;
	NSMutableArray* _TaxList;
	NSString* _Time;
	NSDecimalNumber* _TotalAmount;
	NSString* _Type;
	NSString* _TypeLabel;
	NSString* _User;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSDate* AcceptanceDate;
	@property (strong, nonatomic) NSString* CircumstanceCode;
	@property (strong, nonatomic) NSString* CircumstanceLabel;
	@property (strong, nonatomic) CSCClaimCause* ClaimCause;
	@property (strong, nonatomic) NSMutableArray* ClaimFolderList;
	@property (strong, nonatomic) NSMutableArray* ClaimPartyList;
	@property (strong, nonatomic) NSDate* Date;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) CSCInsuredRisk* InsuredRisk;
	@property (strong, nonatomic) NSDate* LearnedAboutDate;
	@property (strong, nonatomic) NSString* Liability;
	@property (strong, nonatomic) NSString* Location;
	@property (strong, nonatomic) CSCPostalAddress* LocationAddress;
	@property (strong, nonatomic) CSCLoss* Loss;
	@property (strong, nonatomic) NSDate* NotificationDate;
	@property (strong, nonatomic) NSMutableArray* OperationList;
	@property (strong, nonatomic) CSCPerson* Owner;
	@property (strong, nonatomic) NSMutableArray* PeriodList;
	@property (strong, nonatomic) NSString* PlaceCode;
	@property (strong, nonatomic) NSString* PlaceLabel;
	@property int RejectCount;
	@property (strong, nonatomic) NSMutableArray* RelatedFolderList;
	@property (strong, nonatomic) NSMutableArray* Remark;
	@property (strong, nonatomic) NSMutableArray* RoleList;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSDate* StatusDate;
	@property (strong, nonatomic) NSString* StatusLabel;
	@property (strong, nonatomic) NSString* StatusMotive;
	@property (strong, nonatomic) NSString* StatusMotiveLabel;
	@property (strong, nonatomic) NSMutableArray* TaxList;
	@property (strong, nonatomic) NSString* Time;
	@property (strong, nonatomic) NSDecimalNumber* TotalAmount;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* TypeLabel;
	@property (strong, nonatomic) NSString* User;

	+ (CSCClaimEvent*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
