/*
	CSCClaimVictim.h
	The implementation of properties and methods for the CSCClaimVictim object.
	Generated by SudzC.com
*/
#import "CSCClaimVictim.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCInsurer.h"
#import "CSCDebt.h"
#import "CSCDebt.h"
#import "CSCDebt.h"
#import "CSCArrayOfInjuryCompensation.h"
#import "CSCArrayOfLesion.h"
#import "CSCArrayOfMedicalReport.h"
#import "CSCInsurer.h"
#import "CSCArrayOfString.h"
@implementation CSCClaimVictim
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize AccidentType = _AccidentType;
	@synthesize AssignedInsurer = _AssignedInsurer;
	@synthesize BirthDate = _BirthDate;
	@synthesize CadreIndemnisation = _CadreIndemnisation;
	@synthesize CasIRCA = _CasIRCA;
	@synthesize CasPAOS = _CasPAOS;
	@synthesize CompensationRightRate = _CompensationRightRate;
	@synthesize CurrencyCode = _CurrencyCode;
	@synthesize DeathDate = _DeathDate;
	@synthesize DisabilityLevel = _DisabilityLevel;
	@synthesize EmployerDebt = _EmployerDebt;
	@synthesize FirstCertificateDate = _FirstCertificateDate;
	@synthesize FolderInspector = _FolderInspector;
	@synthesize Gender = _Gender;
	@synthesize HealthInsuranceDebt = _HealthInsuranceDebt;
	@synthesize HealthInsured = _HealthInsured;
	@synthesize HealthSchemeDebt = _HealthSchemeDebt;
	@synthesize HospitalDuration = _HospitalDuration;
	@synthesize Hospitalization = _Hospitalization;
	@synthesize InjuryCompensationList = _InjuryCompensationList;
	@synthesize KeepSalary = _KeepSalary;
	@synthesize LesionList = _LesionList;
	@synthesize Liability = _Liability;
	@synthesize MaritalStatus = _MaritalStatus;
	@synthesize MedicalEndDate = _MedicalEndDate;
	@synthesize MedicalReportList = _MedicalReportList;
	@synthesize MissingAnswer = _MissingAnswer;
	@synthesize NetIncome = _NetIncome;
	@synthesize OffWorkDuration = _OffWorkDuration;
	@synthesize PlafondRecours = _PlafondRecours;
	@synthesize PriorMedicalCondition = _PriorMedicalCondition;
	@synthesize Profession = _Profession;
	@synthesize ProfessionalDamage = _ProfessionalDamage;
	@synthesize PublicLiabilityInsurer = _PublicLiabilityInsurer;
	@synthesize RecoveryDate = _RecoveryDate;
	@synthesize SocialInsured = _SocialInsured;
	@synthesize SocialSecurityKey = _SocialSecurityKey;
	@synthesize SocialSecurityNumber = _SocialSecurityNumber;
	@synthesize Text = _Text;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.AccidentType = nil;
			self.AssignedInsurer = nil; // [[CSCInsurer alloc] init];
			self.BirthDate = nil;
			self.CadreIndemnisation = nil;
			self.CasIRCA = nil;
			self.CasPAOS = nil;
			self.CompensationRightRate = nil;
			self.CurrencyCode = nil;
			self.DeathDate = nil;
			self.DisabilityLevel = nil;
			self.EmployerDebt = nil; // [[CSCDebt alloc] init];
			self.FirstCertificateDate = nil;
			self.FolderInspector = nil;
			self.Gender = nil;
			self.HealthInsuranceDebt = nil; // [[CSCDebt alloc] init];
			self.HealthInsured = nil;
			self.HealthSchemeDebt = nil; // [[CSCDebt alloc] init];
			self.InjuryCompensationList = [[NSMutableArray alloc] init];
			self.LesionList = [[NSMutableArray alloc] init];
			self.Liability = nil;
			self.MaritalStatus = nil;
			self.MedicalEndDate = nil;
			self.MedicalReportList = [[NSMutableArray alloc] init];
			self.NetIncome = nil;
			self.PlafondRecours = nil;
			self.Profession = nil;
			self.PublicLiabilityInsurer = nil; // [[CSCInsurer alloc] init];
			self.RecoveryDate = nil;
			self.SocialSecurityKey = nil;
			self.SocialSecurityNumber = nil;
			self.Text = [[NSMutableArray alloc] init];

		}
		return self;
	}

	+ (CSCClaimVictim*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCClaimVictim*)[[CSCClaimVictim alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.AccidentType = [Soap getNodeValue: node withName: @"AccidentType"];
			self.AssignedInsurer = [[CSCInsurer createWithNode: [Soap getNode: node withName: @"AssignedInsurer"]] object];
			self.BirthDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"BirthDate"]];
			self.CadreIndemnisation = [Soap getNodeValue: node withName: @"CadreIndemnisation"];
			self.CasIRCA = [Soap getNodeValue: node withName: @"CasIRCA"];
			self.CasPAOS = [Soap getNodeValue: node withName: @"CasPAOS"];
			self.CompensationRightRate = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"CompensationRightRate"]];
			self.CurrencyCode = [Soap getNodeValue: node withName: @"CurrencyCode"];
			self.DeathDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"DeathDate"]];
			self.DisabilityLevel = [Soap getNodeValue: node withName: @"DisabilityLevel"];
			self.EmployerDebt = [[CSCDebt createWithNode: [Soap getNode: node withName: @"EmployerDebt"]] object];
			self.FirstCertificateDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"FirstCertificateDate"]];
			self.FolderInspector = [Soap getNodeValue: node withName: @"FolderInspector"];
			self.Gender = [Soap getNodeValue: node withName: @"Gender"];
			self.HealthInsuranceDebt = [[CSCDebt createWithNode: [Soap getNode: node withName: @"HealthInsuranceDebt"]] object];
			self.HealthInsured = [Soap getNodeValue: node withName: @"HealthInsured"];
			self.HealthSchemeDebt = [[CSCDebt createWithNode: [Soap getNode: node withName: @"HealthSchemeDebt"]] object];
			self.HospitalDuration = [[Soap getNodeValue: node withName: @"HospitalDuration"] intValue];
			self.Hospitalization = [[Soap getNodeValue: node withName: @"Hospitalization"] boolValue];
			self.InjuryCompensationList = [[CSCArrayOfInjuryCompensation createWithNode: [Soap getNode: node withName: @"InjuryCompensationList"]] object];
			self.KeepSalary = [[Soap getNodeValue: node withName: @"KeepSalary"] boolValue];
			self.LesionList = [[CSCArrayOfLesion createWithNode: [Soap getNode: node withName: @"LesionList"]] object];
			self.Liability = [Soap getNodeValue: node withName: @"Liability"];
			self.MaritalStatus = [Soap getNodeValue: node withName: @"MaritalStatus"];
			self.MedicalEndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"MedicalEndDate"]];
			self.MedicalReportList = [[CSCArrayOfMedicalReport createWithNode: [Soap getNode: node withName: @"MedicalReportList"]] object];
			self.MissingAnswer = [[Soap getNodeValue: node withName: @"MissingAnswer"] boolValue];
			self.NetIncome = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"NetIncome"]];
			self.OffWorkDuration = [[Soap getNodeValue: node withName: @"OffWorkDuration"] intValue];
			self.PlafondRecours = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"PlafondRecours"]];
			self.PriorMedicalCondition = [[Soap getNodeValue: node withName: @"PriorMedicalCondition"] boolValue];
			self.Profession = [Soap getNodeValue: node withName: @"Profession"];
			self.ProfessionalDamage = [[Soap getNodeValue: node withName: @"ProfessionalDamage"] boolValue];
			self.PublicLiabilityInsurer = [[CSCInsurer createWithNode: [Soap getNode: node withName: @"PublicLiabilityInsurer"]] object];
			self.RecoveryDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"RecoveryDate"]];
			self.SocialInsured = [[Soap getNodeValue: node withName: @"SocialInsured"] boolValue];
			self.SocialSecurityKey = [Soap getNodeValue: node withName: @"SocialSecurityKey"];
			self.SocialSecurityNumber = [Soap getNodeValue: node withName: @"SocialSecurityNumber"];
			self.Text = [[CSCArrayOfString createWithNode: [Soap getNode: node withName: @"Text"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"ClaimVictim"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.AccidentType != nil) [s appendFormat: @"<AccidentType>%@</AccidentType>", [[self.AccidentType stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.AssignedInsurer != nil) [s appendString: [self.AssignedInsurer serialize: @"AssignedInsurer"]];
		if (self.BirthDate != nil) [s appendFormat: @"<BirthDate>%@</BirthDate>", [Soap getDateString: self.BirthDate]];
		if (self.CadreIndemnisation != nil) [s appendFormat: @"<CadreIndemnisation>%@</CadreIndemnisation>", [[self.CadreIndemnisation stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.CasIRCA != nil) [s appendFormat: @"<CasIRCA>%@</CasIRCA>", [[self.CasIRCA stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.CasPAOS != nil) [s appendFormat: @"<CasPAOS>%@</CasPAOS>", [[self.CasPAOS stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.CompensationRightRate != nil) [s appendFormat: @"<CompensationRightRate>%@</CompensationRightRate>", [NSString stringWithFormat: @"%@", self.CompensationRightRate]];
		if (self.CurrencyCode != nil) [s appendFormat: @"<CurrencyCode>%@</CurrencyCode>", [[self.CurrencyCode stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.DeathDate != nil) [s appendFormat: @"<DeathDate>%@</DeathDate>", [Soap getDateString: self.DeathDate]];
		if (self.DisabilityLevel != nil) [s appendFormat: @"<DisabilityLevel>%@</DisabilityLevel>", [[self.DisabilityLevel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.EmployerDebt != nil) [s appendString: [self.EmployerDebt serialize: @"EmployerDebt"]];
		if (self.FirstCertificateDate != nil) [s appendFormat: @"<FirstCertificateDate>%@</FirstCertificateDate>", [Soap getDateString: self.FirstCertificateDate]];
		if (self.FolderInspector != nil) [s appendFormat: @"<FolderInspector>%@</FolderInspector>", [[self.FolderInspector stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.Gender != nil) [s appendFormat: @"<Gender>%@</Gender>", [[self.Gender stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.HealthInsuranceDebt != nil) [s appendString: [self.HealthInsuranceDebt serialize: @"HealthInsuranceDebt"]];
		if (self.HealthInsured != nil) [s appendFormat: @"<HealthInsured>%@</HealthInsured>", [[self.HealthInsured stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.HealthSchemeDebt != nil) [s appendString: [self.HealthSchemeDebt serialize: @"HealthSchemeDebt"]];
		[s appendFormat: @"<HospitalDuration>%@</HospitalDuration>", [NSString stringWithFormat: @"%i", self.HospitalDuration]];
		[s appendFormat: @"<Hospitalization>%@</Hospitalization>", (self.Hospitalization)?@"true":@"false"];
		if (self.InjuryCompensationList != nil && self.InjuryCompensationList.count > 0) {
			[s appendFormat: @"<InjuryCompensationList>%@</InjuryCompensationList>", [CSCArrayOfInjuryCompensation serialize: self.InjuryCompensationList]];
		} else {
			[s appendString: @"<InjuryCompensationList/>"];
		}
		[s appendFormat: @"<KeepSalary>%@</KeepSalary>", (self.KeepSalary)?@"true":@"false"];
		if (self.LesionList != nil && self.LesionList.count > 0) {
			[s appendFormat: @"<LesionList>%@</LesionList>", [CSCArrayOfLesion serialize: self.LesionList]];
		} else {
			[s appendString: @"<LesionList/>"];
		}
		if (self.Liability != nil) [s appendFormat: @"<Liability>%@</Liability>", [[self.Liability stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MaritalStatus != nil) [s appendFormat: @"<MaritalStatus>%@</MaritalStatus>", [[self.MaritalStatus stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MedicalEndDate != nil) [s appendFormat: @"<MedicalEndDate>%@</MedicalEndDate>", [Soap getDateString: self.MedicalEndDate]];
		if (self.MedicalReportList != nil && self.MedicalReportList.count > 0) {
			[s appendFormat: @"<MedicalReportList>%@</MedicalReportList>", [CSCArrayOfMedicalReport serialize: self.MedicalReportList]];
		} else {
			[s appendString: @"<MedicalReportList/>"];
		}
		[s appendFormat: @"<MissingAnswer>%@</MissingAnswer>", (self.MissingAnswer)?@"true":@"false"];
		if (self.NetIncome != nil) [s appendFormat: @"<NetIncome>%@</NetIncome>", [NSString stringWithFormat: @"%@", self.NetIncome]];
		[s appendFormat: @"<OffWorkDuration>%@</OffWorkDuration>", [NSString stringWithFormat: @"%i", self.OffWorkDuration]];
		if (self.PlafondRecours != nil) [s appendFormat: @"<PlafondRecours>%@</PlafondRecours>", [NSString stringWithFormat: @"%@", self.PlafondRecours]];
		[s appendFormat: @"<PriorMedicalCondition>%@</PriorMedicalCondition>", (self.PriorMedicalCondition)?@"true":@"false"];
		if (self.Profession != nil) [s appendFormat: @"<Profession>%@</Profession>", [[self.Profession stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		[s appendFormat: @"<ProfessionalDamage>%@</ProfessionalDamage>", (self.ProfessionalDamage)?@"true":@"false"];
		if (self.PublicLiabilityInsurer != nil) [s appendString: [self.PublicLiabilityInsurer serialize: @"PublicLiabilityInsurer"]];
		if (self.RecoveryDate != nil) [s appendFormat: @"<RecoveryDate>%@</RecoveryDate>", [Soap getDateString: self.RecoveryDate]];
		[s appendFormat: @"<SocialInsured>%@</SocialInsured>", (self.SocialInsured)?@"true":@"false"];
		if (self.SocialSecurityKey != nil) [s appendFormat: @"<SocialSecurityKey>%@</SocialSecurityKey>", [[self.SocialSecurityKey stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.SocialSecurityNumber != nil) [s appendFormat: @"<SocialSecurityNumber>%@</SocialSecurityNumber>", [[self.SocialSecurityNumber stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.Text != nil && self.Text.count > 0) {
			[s appendFormat: @"<Text>%@</Text>", [CSCArrayOfString serialize: self.Text]];
		} else {
			[s appendString: @"<Text/>"];
		}

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCClaimVictim class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
