/*
	CSCClaimFolder.h
	The implementation of properties and methods for the CSCClaimFolder object.
	Generated by SudzC.com
*/
#import "CSCClaimFolder.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCClaimDeathTax.h"
#import "CSCClaimEvent.h"
#import "CSCClaimParty.h"
#import "CSCClaimReserve.h"
#import "CSCClaimReserve.h"
#import "CSCArrayOfSettlementFolder.h"
@implementation CSCClaimFolder
	@synthesize DisplayId = _DisplayId;
	@synthesize EffectiveDate = _EffectiveDate;
	@synthesize EndDate = _EndDate;
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize StartDate = _StartDate;
	@synthesize AcceptanceDate = _AcceptanceDate;
	@synthesize ClaimDeathTax = _ClaimDeathTax;
	@synthesize ClaimEvent = _ClaimEvent;
	@synthesize ClaimParty = _ClaimParty;
	@synthesize CompensationReserve = _CompensationReserve;
	@synthesize ContractNumber = _ContractNumber;
	@synthesize FeesReserve = _FeesReserve;
	@synthesize Identifier = _Identifier;
	@synthesize ProductIdentifier = _ProductIdentifier;
	@synthesize ProductLabel = _ProductLabel;
	@synthesize Provision = _Provision;
	@synthesize Recourse = _Recourse;
	@synthesize SearchCoverageDate = _SearchCoverageDate;
	@synthesize SettlementFolderList = _SettlementFolderList;
	@synthesize Status = _Status;
	@synthesize StatusDate = _StatusDate;
	@synthesize StatusLabel = _StatusLabel;
	@synthesize StatusMotive = _StatusMotive;
	@synthesize StatusMotiveLabel = _StatusMotiveLabel;
	@synthesize TotalAmount = _TotalAmount;
	@synthesize TotalAmount2 = _TotalAmount2;
	@synthesize TotalRecoveryAmount = _TotalRecoveryAmount;

	- (id) init
	{
		if(self = [super init])
		{
			self.DisplayId = nil;
			self.EffectiveDate = nil;
			self.EndDate = nil;
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.StartDate = nil;
			self.AcceptanceDate = nil;
			self.ClaimDeathTax = nil; // [[CSCClaimDeathTax alloc] init];
			self.ClaimEvent = nil; // [[CSCClaimEvent alloc] init];
			self.ClaimParty = nil; // [[CSCClaimParty alloc] init];
			self.CompensationReserve = nil;
			self.ContractNumber = nil;
			self.FeesReserve = nil;
			self.Identifier = nil;
			self.ProductIdentifier = nil;
			self.ProductLabel = nil;
			self.Provision = nil; // [[CSCClaimReserve alloc] init];
			self.Recourse = nil; // [[CSCClaimReserve alloc] init];
			self.SearchCoverageDate = nil;
			self.SettlementFolderList = [[NSMutableArray alloc] init];
			self.Status = nil;
			self.StatusDate = nil;
			self.StatusLabel = nil;
			self.StatusMotive = nil;
			self.StatusMotiveLabel = nil;
			self.TotalAmount = nil;
			self.TotalAmount2 = nil;
			self.TotalRecoveryAmount = nil;

		}
		return self;
	}

	+ (CSCClaimFolder*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCClaimFolder*)[[CSCClaimFolder alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.DisplayId = [Soap getNodeValue: node withName: @"DisplayId"];
			self.EffectiveDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EffectiveDate"]];
			self.EndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EndDate"]];
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.StartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"StartDate"]];
			self.AcceptanceDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"AcceptanceDate"]];
			self.ClaimDeathTax = [[CSCClaimDeathTax createWithNode: [Soap getNode: node withName: @"ClaimDeathTax"]] object];
			self.ClaimEvent = [[CSCClaimEvent createWithNode: [Soap getNode: node withName: @"ClaimEvent"]] object];
			self.ClaimParty = [[CSCClaimParty createWithNode: [Soap getNode: node withName: @"ClaimParty"]] object];
			self.CompensationReserve = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"CompensationReserve"]];
			self.ContractNumber = [Soap getNodeValue: node withName: @"ContractNumber"];
			self.FeesReserve = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"FeesReserve"]];
			self.Identifier = [Soap getNodeValue: node withName: @"Identifier"];
			self.ProductIdentifier = [Soap getNodeValue: node withName: @"ProductIdentifier"];
			self.ProductLabel = [Soap getNodeValue: node withName: @"ProductLabel"];
			self.Provision = [[CSCClaimReserve createWithNode: [Soap getNode: node withName: @"Provision"]] object];
			self.Recourse = [[CSCClaimReserve createWithNode: [Soap getNode: node withName: @"Recourse"]] object];
			self.SearchCoverageDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"SearchCoverageDate"]];
			self.SettlementFolderList = [[CSCArrayOfSettlementFolder createWithNode: [Soap getNode: node withName: @"SettlementFolderList"]] object];
			self.Status = [Soap getNodeValue: node withName: @"Status"];
			self.StatusDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"StatusDate"]];
			self.StatusLabel = [Soap getNodeValue: node withName: @"StatusLabel"];
			self.StatusMotive = [Soap getNodeValue: node withName: @"StatusMotive"];
			self.StatusMotiveLabel = [Soap getNodeValue: node withName: @"StatusMotiveLabel"];
			self.TotalAmount = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"TotalAmount"]];
			self.TotalAmount2 = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"TotalAmount2"]];
			self.TotalRecoveryAmount = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"TotalRecoveryAmount"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"ClaimFolder"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.DisplayId != nil) [s appendFormat: @"<DisplayId>%@</DisplayId>", [[self.DisplayId stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.EffectiveDate != nil) [s appendFormat: @"<EffectiveDate>%@</EffectiveDate>", [Soap getDateString: self.EffectiveDate]];
		if (self.EndDate != nil) [s appendFormat: @"<EndDate>%@</EndDate>", [Soap getDateString: self.EndDate]];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.StartDate != nil) [s appendFormat: @"<StartDate>%@</StartDate>", [Soap getDateString: self.StartDate]];
		if (self.AcceptanceDate != nil) [s appendFormat: @"<AcceptanceDate>%@</AcceptanceDate>", [Soap getDateString: self.AcceptanceDate]];
		if (self.ClaimDeathTax != nil) [s appendString: [self.ClaimDeathTax serialize: @"ClaimDeathTax"]];
		if (self.ClaimEvent != nil) [s appendString: [self.ClaimEvent serialize: @"ClaimEvent"]];
		if (self.ClaimParty != nil) [s appendString: [self.ClaimParty serialize: @"ClaimParty"]];
		if (self.CompensationReserve != nil) [s appendFormat: @"<CompensationReserve>%@</CompensationReserve>", [NSString stringWithFormat: @"%@", self.CompensationReserve]];
		if (self.ContractNumber != nil) [s appendFormat: @"<ContractNumber>%@</ContractNumber>", [[self.ContractNumber stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.FeesReserve != nil) [s appendFormat: @"<FeesReserve>%@</FeesReserve>", [NSString stringWithFormat: @"%@", self.FeesReserve]];
		if (self.Identifier != nil) [s appendFormat: @"<Identifier>%@</Identifier>", [[self.Identifier stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.ProductIdentifier != nil) [s appendFormat: @"<ProductIdentifier>%@</ProductIdentifier>", [[self.ProductIdentifier stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.ProductLabel != nil) [s appendFormat: @"<ProductLabel>%@</ProductLabel>", [[self.ProductLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.Provision != nil) [s appendString: [self.Provision serialize: @"Provision"]];
		if (self.Recourse != nil) [s appendString: [self.Recourse serialize: @"Recourse"]];
		if (self.SearchCoverageDate != nil) [s appendFormat: @"<SearchCoverageDate>%@</SearchCoverageDate>", [Soap getDateString: self.SearchCoverageDate]];
		if (self.SettlementFolderList != nil && self.SettlementFolderList.count > 0) {
			[s appendFormat: @"<SettlementFolderList>%@</SettlementFolderList>", [CSCArrayOfSettlementFolder serialize: self.SettlementFolderList]];
		} else {
			[s appendString: @"<SettlementFolderList/>"];
		}
		if (self.Status != nil) [s appendFormat: @"<Status>%@</Status>", [[self.Status stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.StatusDate != nil) [s appendFormat: @"<StatusDate>%@</StatusDate>", [Soap getDateString: self.StatusDate]];
		if (self.StatusLabel != nil) [s appendFormat: @"<StatusLabel>%@</StatusLabel>", [[self.StatusLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.StatusMotive != nil) [s appendFormat: @"<StatusMotive>%@</StatusMotive>", [[self.StatusMotive stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.StatusMotiveLabel != nil) [s appendFormat: @"<StatusMotiveLabel>%@</StatusMotiveLabel>", [[self.StatusMotiveLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.TotalAmount != nil) [s appendFormat: @"<TotalAmount>%@</TotalAmount>", [NSString stringWithFormat: @"%@", self.TotalAmount]];
		if (self.TotalAmount2 != nil) [s appendFormat: @"<TotalAmount2>%@</TotalAmount2>", [NSString stringWithFormat: @"%@", self.TotalAmount2]];
		if (self.TotalRecoveryAmount != nil) [s appendFormat: @"<TotalRecoveryAmount>%@</TotalRecoveryAmount>", [NSString stringWithFormat: @"%@", self.TotalRecoveryAmount]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCClaimFolder class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
