/*
	CSCCoverageFund.h
	The interface definition of properties and methods for the CSCCoverageFund object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfBeneficiary;
@class CSCArrayOfClause;
@class CSCInterestFund;
@class CSCArrayOfPenaltyRate;
@class CSCArrayOfSavingsFlow;
@class CSCSavingsPool;
@class CSCUnitLinkedFund;
#import "CSCObject.h"
@class CSCObject;


@interface CSCCoverageFund : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSMutableArray* _BeneficiaryList;
	NSMutableArray* _ClauseList;
	NSString* _Eligibility;
	NSString* _Identifier;
	NSString* _Label;
	BOOL _Mandatory;
	int _Number;
	NSDecimalNumber* _GrossCashValue;
	CSCInterestFund* _InterestFund;
	NSDecimalNumber* _NetCashValue;
	NSMutableArray* _PenaltyRateList;
	NSDecimalNumber* _SavingsCalculation;
	NSMutableArray* _SavingsFlowList;
	CSCSavingsPool* _SavingsPool;
	NSString* _Type;
	CSCUnitLinkedFund* _UnitLinkedFund;
	NSDecimalNumber* _Units;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSMutableArray* BeneficiaryList;
	@property (strong, nonatomic) NSMutableArray* ClauseList;
	@property (strong, nonatomic) NSString* Eligibility;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) NSString* Label;
	@property BOOL Mandatory;
	@property int Number;
	@property (strong, nonatomic) NSDecimalNumber* GrossCashValue;
	@property (strong, nonatomic) CSCInterestFund* InterestFund;
	@property (strong, nonatomic) NSDecimalNumber* NetCashValue;
	@property (strong, nonatomic) NSMutableArray* PenaltyRateList;
	@property (strong, nonatomic) NSDecimalNumber* SavingsCalculation;
	@property (strong, nonatomic) NSMutableArray* SavingsFlowList;
	@property (strong, nonatomic) CSCSavingsPool* SavingsPool;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) CSCUnitLinkedFund* UnitLinkedFund;
	@property (strong, nonatomic) NSDecimalNumber* Units;

	+ (CSCCoverageFund*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
