/*
	CSCCreditCard.h
	The interface definition of properties and methods for the CSCCreditCard object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCOrganization;
@class CSCPerson;
#import "CSCObject.h"
@class CSCObject;


@interface CSCCreditCard : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSString* _AddressCategory;
	NSString* _AddressCategoryLabel;
	NSString* _AddressIdentifier;
	BOOL _Confidential;
	BOOL _Invalid;
	CSCOrganization* _Organization;
	CSCPerson* _Person;
	BOOL _Preferred;
	NSString* _CountryCode;
	NSString* _CVVNumber;
	NSString* _CardHolderName;
	NSString* _CardNumber;
	NSString* _CardType;
	NSString* _CurrencyCode;
	NSString* _ExchangeLevel;
	NSDate* _ExpiryDate;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSString* AddressCategory;
	@property (strong, nonatomic) NSString* AddressCategoryLabel;
	@property (strong, nonatomic) NSString* AddressIdentifier;
	@property BOOL Confidential;
	@property BOOL Invalid;
	@property (strong, nonatomic) CSCOrganization* Organization;
	@property (strong, nonatomic) CSCPerson* Person;
	@property BOOL Preferred;
	@property (strong, nonatomic) NSString* CountryCode;
	@property (strong, nonatomic) NSString* CVVNumber;
	@property (strong, nonatomic) NSString* CardHolderName;
	@property (strong, nonatomic) NSString* CardNumber;
	@property (strong, nonatomic) NSString* CardType;
	@property (strong, nonatomic) NSString* CurrencyCode;
	@property (strong, nonatomic) NSString* ExchangeLevel;
	@property (strong, nonatomic) NSDate* ExpiryDate;

	+ (CSCCreditCard*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
