/*
	CSCCoverage.h
	The interface definition of properties and methods for the CSCCoverage object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfBeneficiary;
@class CSCArrayOfClause;
@class CSCBankingLoan;
@class CSCArrayOfBenefitItem;
@class CSCContract;
@class CSCDeathCoverage;
@class CSCHealthCoverageDetail;
@class CSCIndexation;
@class CSCArrayOfMembership;
#import "CSCObject.h"
@class CSCObject;


@interface CSCCoverage : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSMutableArray* _BeneficiaryList;
	NSMutableArray* _ClauseList;
	NSString* _Eligibility;
	NSString* _Identifier;
	NSString* _Label;
	BOOL _Mandatory;
	int _Number;
	NSDecimalNumber* _Amount;
	NSString* _AmountType;
	CSCBankingLoan* _BankingLoan;
	NSMutableArray* _BenefitItemList;
	int _BillingDuration;
	NSString* _BillingDurationUnit;
	NSDate* _BillingEndDate;
	NSDate* _BillingStartDate;
	CSCContract* _Contract;
	CSCDeathCoverage* _DeathCoverage;
	NSString* _DeductibleClause;
	int _DefinitionNumber;
	int _Duration;
	CSCHealthCoverageDetail* _HealthCoverageDetail;
	CSCIndexation* _Indexation;
	NSString* _IndexationClause;
	int _MaximumAge;
	NSMutableArray* _MembershipList;
	int _MinimumAge;
	NSString* _RiskCode;
	int _SettlementDuration;
	NSString* _SettlementDurationUnit;
	NSDate* _SettlementEndDate;
	NSString* _TaxClause;
	NSString* _Type;
	NSString* _WaitingPeriodClause;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSMutableArray* BeneficiaryList;
	@property (strong, nonatomic) NSMutableArray* ClauseList;
	@property (strong, nonatomic) NSString* Eligibility;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) NSString* Label;
	@property BOOL Mandatory;
	@property int Number;
	@property (strong, nonatomic) NSDecimalNumber* Amount;
	@property (strong, nonatomic) NSString* AmountType;
	@property (strong, nonatomic) CSCBankingLoan* BankingLoan;
	@property (strong, nonatomic) NSMutableArray* BenefitItemList;
	@property int BillingDuration;
	@property (strong, nonatomic) NSString* BillingDurationUnit;
	@property (strong, nonatomic) NSDate* BillingEndDate;
	@property (strong, nonatomic) NSDate* BillingStartDate;
	@property (strong, nonatomic) CSCContract* Contract;
	@property (strong, nonatomic) CSCDeathCoverage* DeathCoverage;
	@property (strong, nonatomic) NSString* DeductibleClause;
	@property int DefinitionNumber;
	@property int Duration;
	@property (strong, nonatomic) CSCHealthCoverageDetail* HealthCoverageDetail;
	@property (strong, nonatomic) CSCIndexation* Indexation;
	@property (strong, nonatomic) NSString* IndexationClause;
	@property int MaximumAge;
	@property (strong, nonatomic) NSMutableArray* MembershipList;
	@property int MinimumAge;
	@property (strong, nonatomic) NSString* RiskCode;
	@property int SettlementDuration;
	@property (strong, nonatomic) NSString* SettlementDurationUnit;
	@property (strong, nonatomic) NSDate* SettlementEndDate;
	@property (strong, nonatomic) NSString* TaxClause;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* WaitingPeriodClause;

	+ (CSCCoverage*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
