/*
	CSCClause.h
	The interface definition of properties and methods for the CSCClause object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCCoverage;
@class CSCArrayOfString;
#import "CSCObject.h"
@class CSCObject;


@interface CSCClause : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSString* _Code;
	CSCCoverage* _Coverage;
	NSString* _Label;
	BOOL _Modifiable;
	NSString* _Text;
	NSMutableArray* _TextList;
	NSString* _Type;
	NSString* _TypeLabel;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSString* Code;
	@property (strong, nonatomic) CSCCoverage* Coverage;
	@property (strong, nonatomic) NSString* Label;
	@property BOOL Modifiable;
	@property (strong, nonatomic) NSString* Text;
	@property (strong, nonatomic) NSMutableArray* TextList;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* TypeLabel;

	+ (CSCClause*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
