/*
	CSCDebt.h
	The implementation of properties and methods for the CSCDebt object.
	Generated by SudzC.com
*/
#import "CSCDebt.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
@implementation CSCDebt
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize Amount = _Amount;
	@synthesize Final = _Final;
	@synthesize FinalPayment = _FinalPayment;
	@synthesize Payment = _Payment;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.Amount = nil;
			self.Payment = nil;

		}
		return self;
	}

	+ (CSCDebt*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCDebt*)[[CSCDebt alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.Amount = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"Amount"]];
			self.Final = [[Soap getNodeValue: node withName: @"Final"] boolValue];
			self.FinalPayment = [[Soap getNodeValue: node withName: @"FinalPayment"] boolValue];
			self.Payment = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"Payment"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Debt"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.Amount != nil) [s appendFormat: @"<Amount>%@</Amount>", [NSString stringWithFormat: @"%@", self.Amount]];
		[s appendFormat: @"<Final>%@</Final>", (self.Final)?@"true":@"false"];
		[s appendFormat: @"<FinalPayment>%@</FinalPayment>", (self.FinalPayment)?@"true":@"false"];
		if (self.Payment != nil) [s appendFormat: @"<Payment>%@</Payment>", [NSString stringWithFormat: @"%@", self.Payment]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCDebt class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
