/*
	CSCFormulaDfn.h
	The interface definition of properties and methods for the CSCFormulaDfn object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCArrayOfVariableDfn;
@class CSCArrayOfVariableDfn;
#import "CSCObject.h"
@class CSCObject;


@interface CSCFormulaDfn : CSCObject
{
	NSString* _Identifier;
	NSMutableArray* _InputVariableList;
	NSString* _Label;
	NSMutableArray* _OutputVariableList;
	
}
		
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) NSMutableArray* InputVariableList;
	@property (strong, nonatomic) NSString* Label;
	@property (strong, nonatomic) NSMutableArray* OutputVariableList;

	+ (CSCFormulaDfn*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
