/*
	CSCFormulaDfn.h
	The implementation of properties and methods for the CSCFormulaDfn object.
	Generated by SudzC.com
*/
#import "CSCFormulaDfn.h"

#import "CSCArrayOfVariableDfn.h"
#import "CSCArrayOfVariableDfn.h"
@implementation CSCFormulaDfn
	@synthesize Identifier = _Identifier;
	@synthesize InputVariableList = _InputVariableList;
	@synthesize Label = _Label;
	@synthesize OutputVariableList = _OutputVariableList;

	- (id) init
	{
		if(self = [super init])
		{
			self.Identifier = nil;
			self.InputVariableList = [[NSMutableArray alloc] init];
			self.Label = nil;
			self.OutputVariableList = [[NSMutableArray alloc] init];

		}
		return self;
	}

	+ (CSCFormulaDfn*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCFormulaDfn*)[[CSCFormulaDfn alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Identifier = [Soap getNodeValue: node withName: @"Identifier"];
			self.InputVariableList = [[CSCArrayOfVariableDfn createWithNode: [Soap getNode: node withName: @"InputVariableList"]] object];
			self.Label = [Soap getNodeValue: node withName: @"Label"];
			self.OutputVariableList = [[CSCArrayOfVariableDfn createWithNode: [Soap getNode: node withName: @"OutputVariableList"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"FormulaDfn"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Identifier != nil) [s appendFormat: @"<Identifier>%@</Identifier>", [[self.Identifier stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.InputVariableList != nil && self.InputVariableList.count > 0) {
			[s appendFormat: @"<InputVariableList>%@</InputVariableList>", [CSCArrayOfVariableDfn serialize: self.InputVariableList]];
		} else {
			[s appendString: @"<InputVariableList/>"];
		}
		if (self.Label != nil) [s appendFormat: @"<Label>%@</Label>", [[self.Label stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.OutputVariableList != nil && self.OutputVariableList.count > 0) {
			[s appendFormat: @"<OutputVariableList>%@</OutputVariableList>", [CSCArrayOfVariableDfn serialize: self.OutputVariableList]];
		} else {
			[s appendString: @"<OutputVariableList/>"];
		}

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCFormulaDfn class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
