/*
	CSCFinancialActivity.h
	The implementation of properties and methods for the CSCFinancialActivity object.
	Generated by SudzC.com
*/
#import "CSCFinancialActivity.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
@implementation CSCFinancialActivity
	@synthesize DisplayId = _DisplayId;
	@synthesize EffectiveDate = _EffectiveDate;
	@synthesize EndDate = _EndDate;
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize StartDate = _StartDate;
	@synthesize OperationIdentifier1 = _OperationIdentifier1;
	@synthesize OperationIdentifier2 = _OperationIdentifier2;
	@synthesize OperationType1 = _OperationType1;
	@synthesize OperationType2 = _OperationType2;

	- (id) init
	{
		if(self = [super init])
		{
			self.DisplayId = nil;
			self.EffectiveDate = nil;
			self.EndDate = nil;
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.StartDate = nil;
			self.OperationIdentifier1 = nil;
			self.OperationIdentifier2 = nil;
			self.OperationType1 = nil;
			self.OperationType2 = nil;

		}
		return self;
	}

	+ (CSCFinancialActivity*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCFinancialActivity*)[[CSCFinancialActivity alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.DisplayId = [Soap getNodeValue: node withName: @"DisplayId"];
			self.EffectiveDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EffectiveDate"]];
			self.EndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EndDate"]];
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.StartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"StartDate"]];
			self.OperationIdentifier1 = [Soap getNodeValue: node withName: @"OperationIdentifier1"];
			self.OperationIdentifier2 = [Soap getNodeValue: node withName: @"OperationIdentifier2"];
			self.OperationType1 = [Soap getNodeValue: node withName: @"OperationType1"];
			self.OperationType2 = [Soap getNodeValue: node withName: @"OperationType2"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"FinancialActivity"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.DisplayId != nil) [s appendFormat: @"<DisplayId>%@</DisplayId>", [[self.DisplayId stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.EffectiveDate != nil) [s appendFormat: @"<EffectiveDate>%@</EffectiveDate>", [Soap getDateString: self.EffectiveDate]];
		if (self.EndDate != nil) [s appendFormat: @"<EndDate>%@</EndDate>", [Soap getDateString: self.EndDate]];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.StartDate != nil) [s appendFormat: @"<StartDate>%@</StartDate>", [Soap getDateString: self.StartDate]];
		if (self.OperationIdentifier1 != nil) [s appendFormat: @"<OperationIdentifier1>%@</OperationIdentifier1>", [[self.OperationIdentifier1 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.OperationIdentifier2 != nil) [s appendFormat: @"<OperationIdentifier2>%@</OperationIdentifier2>", [[self.OperationIdentifier2 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.OperationType1 != nil) [s appendFormat: @"<OperationType1>%@</OperationType1>", [[self.OperationType1 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.OperationType2 != nil) [s appendFormat: @"<OperationType2>%@</OperationType2>", [[self.OperationType2 stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCFinancialActivity class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
