/*
	CSCFundsAllocation.h
	The interface definition of properties and methods for the CSCFundsAllocation object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfAllocation;
@class CSCArrayOfAllocation;
#import "CSCObject.h"
@class CSCObject;


@interface CSCFundsAllocation : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSMutableArray* _DisinvestmentList;
	NSString* _DisinvestmentMethod;
	NSMutableArray* _InvestmentList;
	NSString* _InvestmentMethod;
	NSString* _Label;
	NSDate* _VersionDate;
	NSString* _VersionNumber;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSMutableArray* DisinvestmentList;
	@property (strong, nonatomic) NSString* DisinvestmentMethod;
	@property (strong, nonatomic) NSMutableArray* InvestmentList;
	@property (strong, nonatomic) NSString* InvestmentMethod;
	@property (strong, nonatomic) NSString* Label;
	@property (strong, nonatomic) NSDate* VersionDate;
	@property (strong, nonatomic) NSString* VersionNumber;

	+ (CSCFundsAllocation*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
