/*
	CSCHouseholdTax.h
	The interface definition of properties and methods for the CSCHouseholdTax object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCHouseholdTax : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	int _ChildrenDependents;
	NSString* _CountryCode;
	NSDate* _FiscalEndDate;
	NSDate* _FiscalStartDate;
	NSString* _IncomeRange;
	NSString* _Residence;
	NSString* _SpouseFullName;
	NSString* _TaxOffice;
	NSString* _TaxType;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property int ChildrenDependents;
	@property (strong, nonatomic) NSString* CountryCode;
	@property (strong, nonatomic) NSDate* FiscalEndDate;
	@property (strong, nonatomic) NSDate* FiscalStartDate;
	@property (strong, nonatomic) NSString* IncomeRange;
	@property (strong, nonatomic) NSString* Residence;
	@property (strong, nonatomic) NSString* SpouseFullName;
	@property (strong, nonatomic) NSString* TaxOffice;
	@property (strong, nonatomic) NSString* TaxType;

	+ (CSCHouseholdTax*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
