/*
	CSCHealthDomain.h
	The interface definition of properties and methods for the CSCHealthDomain object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCHealthDomain : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSString* _CalculationRule;
	NSString* _Channel;
	NSString* _Code;
	int _FootnoteNumber;
	NSString* _Label;
	int _WaitingPeriod;
	
}
		
	@property (retain, nonatomic) CSCObject* Extension;
	@property (retain, nonatomic) NSMutableArray* ExtensionList;
	@property (retain, nonatomic) NSString* CalculationRule;
	@property (retain, nonatomic) NSString* Channel;
	@property (retain, nonatomic) NSString* Code;
	@property int FootnoteNumber;
	@property (retain, nonatomic) NSString* Label;
	@property int WaitingPeriod;

	+ (CSCHealthDomain*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
