/*
	CSCHealthCoverageDetail.h
	The interface definition of properties and methods for the CSCHealthCoverageDetail object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfHealthFormula;
@class CSCArrayOfPartyRole;
#import "CSCObject.h"
@class CSCObject;


@interface CSCHealthCoverageDetail : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	BOOL _AccidentOption;
	BOOL _AccordNoemie;
	NSString* _AssignmentMode;
	NSMutableArray* _FormulaList;
	NSString* _Level;
	BOOL _MaternityOption;
	NSString* _PayeeTitle;
	NSMutableArray* _RoleList;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property BOOL AccidentOption;
	@property BOOL AccordNoemie;
	@property (strong, nonatomic) NSString* AssignmentMode;
	@property (strong, nonatomic) NSMutableArray* FormulaList;
	@property (strong, nonatomic) NSString* Level;
	@property BOOL MaternityOption;
	@property (strong, nonatomic) NSString* PayeeTitle;
	@property (strong, nonatomic) NSMutableArray* RoleList;

	+ (CSCHealthCoverageDetail*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
