/*
	CSCHealthProfessional.h
	The interface definition of properties and methods for the CSCHealthProfessional object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCHealthAddressee;
@class CSCHealthAddressee;
@class CSCHealthAddressee;
#import "CSCObject.h"
@class CSCObject;


@interface CSCHealthProfessional : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	CSCHealthAddressee* _Addressee;
	CSCHealthAddressee* _Primary;
	CSCHealthAddressee* _Secondary;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) CSCHealthAddressee* Addressee;
	@property (strong, nonatomic) CSCHealthAddressee* Primary;
	@property (strong, nonatomic) CSCHealthAddressee* Secondary;

	+ (CSCHealthProfessional*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
