/*
	CSCHealthConditionalLimit.h
	The interface definition of properties and methods for the CSCHealthConditionalLimit object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfHealthCondition;
@class CSCArrayOfHealthLimit;
#import "CSCObject.h"
@class CSCObject;


@interface CSCHealthConditionalLimit : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSMutableArray* _ConditionList;
	BOOL _Cumulative;
	NSMutableArray* _HealthLimitList;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSMutableArray* ConditionList;
	@property BOOL Cumulative;
	@property (strong, nonatomic) NSMutableArray* HealthLimitList;

	+ (CSCHealthConditionalLimit*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
