/*
	CSCHealthProfessional.h
	The implementation of properties and methods for the CSCHealthProfessional object.
	Generated by SudzC.com
*/
#import "CSCHealthProfessional.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCHealthAddressee.h"
#import "CSCHealthAddressee.h"
#import "CSCHealthAddressee.h"
@implementation CSCHealthProfessional
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize Addressee = _Addressee;
	@synthesize Primary = _Primary;
	@synthesize Secondary = _Secondary;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.Addressee = nil; // [[CSCHealthAddressee alloc] init];
			self.Primary = nil; // [[CSCHealthAddressee alloc] init];
			self.Secondary = nil; // [[CSCHealthAddressee alloc] init];

		}
		return self;
	}

	+ (CSCHealthProfessional*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCHealthProfessional*)[[CSCHealthProfessional alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.Addressee = [[CSCHealthAddressee createWithNode: [Soap getNode: node withName: @"Addressee"]] object];
			self.Primary = [[CSCHealthAddressee createWithNode: [Soap getNode: node withName: @"Primary"]] object];
			self.Secondary = [[CSCHealthAddressee createWithNode: [Soap getNode: node withName: @"Secondary"]] object];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"HealthProfessional"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.Addressee != nil) [s appendString: [self.Addressee serialize: @"Addressee"]];
		if (self.Primary != nil) [s appendString: [self.Primary serialize: @"Primary"]];
		if (self.Secondary != nil) [s appendString: [self.Secondary serialize: @"Secondary"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCHealthProfessional class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
