/*
	CSCInjuryCompensation.h
	The interface definition of properties and methods for the CSCInjuryCompensation object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCInjuryCompensation : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDecimalNumber* _Amount;
	NSString* _Code;
	NSString* _Label;
	NSDecimalNumber* _LowerValuation;
	NSDecimalNumber* _MoneyInAmount;
	NSDecimalNumber* _RecoveryAmount;
	NSDecimalNumber* _SettlementAmount;
	NSString* _Type;
	NSString* _TypeLabel;
	NSDecimalNumber* _UpperValuation;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDecimalNumber* Amount;
	@property (strong, nonatomic) NSString* Code;
	@property (strong, nonatomic) NSString* Label;
	@property (strong, nonatomic) NSDecimalNumber* LowerValuation;
	@property (strong, nonatomic) NSDecimalNumber* MoneyInAmount;
	@property (strong, nonatomic) NSDecimalNumber* RecoveryAmount;
	@property (strong, nonatomic) NSDecimalNumber* SettlementAmount;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* TypeLabel;
	@property (strong, nonatomic) NSDecimalNumber* UpperValuation;

	+ (CSCInjuryCompensation*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
