/*
	CSCInterestFund.h
	The interface definition of properties and methods for the CSCInterestFund object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfInterestFundItem;
#import "CSCObject.h"
@class CSCObject;


@interface CSCInterestFund : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSString* _Code;
	NSDecimalNumber* _CurrentRate;
	NSDecimalNumber* _DistributionRate;
	NSDecimalNumber* _EstimatedCashValue;
	NSDecimalNumber* _EstimatedGrossValue;
	NSDecimalNumber* _EstimatedNetValue;
	NSDecimalNumber* _EstimatedRate;
	NSDecimalNumber* _GrossCashValue;
	NSDecimalNumber* _GuaranteedCashValue;
	NSDecimalNumber* _GuaranteedRate;
	NSMutableArray* _ItemList;
	NSDecimalNumber* _MinimumGrossValue;
	NSDecimalNumber* _MinimumNetValue;
	NSDecimalNumber* _NetCashValue;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSString* Code;
	@property (strong, nonatomic) NSDecimalNumber* CurrentRate;
	@property (strong, nonatomic) NSDecimalNumber* DistributionRate;
	@property (strong, nonatomic) NSDecimalNumber* EstimatedCashValue;
	@property (strong, nonatomic) NSDecimalNumber* EstimatedGrossValue;
	@property (strong, nonatomic) NSDecimalNumber* EstimatedNetValue;
	@property (strong, nonatomic) NSDecimalNumber* EstimatedRate;
	@property (strong, nonatomic) NSDecimalNumber* GrossCashValue;
	@property (strong, nonatomic) NSDecimalNumber* GuaranteedCashValue;
	@property (strong, nonatomic) NSDecimalNumber* GuaranteedRate;
	@property (strong, nonatomic) NSMutableArray* ItemList;
	@property (strong, nonatomic) NSDecimalNumber* MinimumGrossValue;
	@property (strong, nonatomic) NSDecimalNumber* MinimumNetValue;
	@property (strong, nonatomic) NSDecimalNumber* NetCashValue;

	+ (CSCInterestFund*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
