/*
	CSCInvoiceItem.h
	The interface definition of properties and methods for the CSCInvoiceItem object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCInvoiceItem : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDecimalNumber* _EffectiveExpenses;
	NSDecimalNumber* _Factor;
	NSString* _MedicalCode;
	NSString* _MedicalCodeDetail;
	NSString* _MedicalCodeLabel;
	NSDate* _MedicalStartDate;
	int _Units;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDecimalNumber* EffectiveExpenses;
	@property (strong, nonatomic) NSDecimalNumber* Factor;
	@property (strong, nonatomic) NSString* MedicalCode;
	@property (strong, nonatomic) NSString* MedicalCodeDetail;
	@property (strong, nonatomic) NSString* MedicalCodeLabel;
	@property (strong, nonatomic) NSDate* MedicalStartDate;
	@property int Units;

	+ (CSCInvoiceItem*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
