/*
	CSCIdentityDocument.h
	The interface definition of properties and methods for the CSCIdentityDocument object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCIdentityDocument : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSString* _Authority;
	NSString* _CodeINSEE;
	NSString* _CountryCode;
	NSDate* _ExpirationDate;
	NSDate* _IssueDate;
	NSString* _IssuePlace;
	NSString* _JobLevel;
	NSString* _NationalNumber;
	NSString* _PersonNumber;
	NSDate* _RegistrationDate;
	NSString* _RegistrationNumber;
	NSString* _SerialNumber;
	NSString* _Series;
	NSString* _SocialSecurityKey;
	NSString* _SocialSecurityNumber;
	NSString* _TaxPayerNumber;
	NSString* _Type;
	BOOL _Valid;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSString* Authority;
	@property (strong, nonatomic) NSString* CodeINSEE;
	@property (strong, nonatomic) NSString* CountryCode;
	@property (strong, nonatomic) NSDate* ExpirationDate;
	@property (strong, nonatomic) NSDate* IssueDate;
	@property (strong, nonatomic) NSString* IssuePlace;
	@property (strong, nonatomic) NSString* JobLevel;
	@property (strong, nonatomic) NSString* NationalNumber;
	@property (strong, nonatomic) NSString* PersonNumber;
	@property (strong, nonatomic) NSDate* RegistrationDate;
	@property (strong, nonatomic) NSString* RegistrationNumber;
	@property (strong, nonatomic) NSString* SerialNumber;
	@property (strong, nonatomic) NSString* Series;
	@property (strong, nonatomic) NSString* SocialSecurityKey;
	@property (strong, nonatomic) NSString* SocialSecurityNumber;
	@property (strong, nonatomic) NSString* TaxPayerNumber;
	@property (strong, nonatomic) NSString* Type;
	@property BOOL Valid;

	+ (CSCIdentityDocument*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
