/*
	CSCInvoiceItem.h
	The implementation of properties and methods for the CSCInvoiceItem object.
	Generated by SudzC.com
*/
#import "CSCInvoiceItem.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
@implementation CSCInvoiceItem
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize EffectiveExpenses = _EffectiveExpenses;
	@synthesize Factor = _Factor;
	@synthesize MedicalCode = _MedicalCode;
	@synthesize MedicalCodeDetail = _MedicalCodeDetail;
	@synthesize MedicalCodeLabel = _MedicalCodeLabel;
	@synthesize MedicalStartDate = _MedicalStartDate;
	@synthesize Units = _Units;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.EffectiveExpenses = nil;
			self.Factor = nil;
			self.MedicalCode = nil;
			self.MedicalCodeDetail = nil;
			self.MedicalCodeLabel = nil;
			self.MedicalStartDate = nil;

		}
		return self;
	}

	+ (CSCInvoiceItem*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCInvoiceItem*)[[CSCInvoiceItem alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.EffectiveExpenses = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"EffectiveExpenses"]];
			self.Factor = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"Factor"]];
			self.MedicalCode = [Soap getNodeValue: node withName: @"MedicalCode"];
			self.MedicalCodeDetail = [Soap getNodeValue: node withName: @"MedicalCodeDetail"];
			self.MedicalCodeLabel = [Soap getNodeValue: node withName: @"MedicalCodeLabel"];
			self.MedicalStartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"MedicalStartDate"]];
			self.Units = [[Soap getNodeValue: node withName: @"Units"] intValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"InvoiceItem"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.EffectiveExpenses != nil) [s appendFormat: @"<EffectiveExpenses>%@</EffectiveExpenses>", [NSString stringWithFormat: @"%@", self.EffectiveExpenses]];
		if (self.Factor != nil) [s appendFormat: @"<Factor>%@</Factor>", [NSString stringWithFormat: @"%@", self.Factor]];
		if (self.MedicalCode != nil) [s appendFormat: @"<MedicalCode>%@</MedicalCode>", [[self.MedicalCode stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MedicalCodeDetail != nil) [s appendFormat: @"<MedicalCodeDetail>%@</MedicalCodeDetail>", [[self.MedicalCodeDetail stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MedicalCodeLabel != nil) [s appendFormat: @"<MedicalCodeLabel>%@</MedicalCodeLabel>", [[self.MedicalCodeLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MedicalStartDate != nil) [s appendFormat: @"<MedicalStartDate>%@</MedicalStartDate>", [Soap getDateString: self.MedicalStartDate]];
		[s appendFormat: @"<Units>%@</Units>", [NSString stringWithFormat: @"%i", self.Units]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCInvoiceItem class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
