/*
	CSCLesion.h
	The interface definition of properties and methods for the CSCLesion object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfAfterEffect;
#import "CSCObject.h"
@class CSCObject;


@interface CSCLesion : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSMutableArray* _AfterEffectList;
	NSString* _Code;
	NSString* _Label;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSMutableArray* AfterEffectList;
	@property (strong, nonatomic) NSString* Code;
	@property (strong, nonatomic) NSString* Label;

	+ (CSCLesion*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
