/*
	CSCLoiMadelin.h
	The interface definition of properties and methods for the CSCLoiMadelin object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCLoiMadelin : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _DateAffiliationVeillesse;
	NSDate* _DateAffiliationVieillesse;
	NSDate* _DateCreationEntreprise;
	NSString* _DebutExerciceFiscal;
	NSString* _DebutExerciceFiscale;
	BOOL _OrigineCoreva;
	BOOL _ReconstitutionCarriere;
	NSString* _StatutAgriculteur;
	NSString* _StatutAssure;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* DateAffiliationVeillesse;
	@property (strong, nonatomic) NSDate* DateAffiliationVieillesse;
	@property (strong, nonatomic) NSDate* DateCreationEntreprise;
	@property (strong, nonatomic) NSString* DebutExerciceFiscal;
	@property (strong, nonatomic) NSString* DebutExerciceFiscale;
	@property BOOL OrigineCoreva;
	@property BOOL ReconstitutionCarriere;
	@property (strong, nonatomic) NSString* StatutAgriculteur;
	@property (strong, nonatomic) NSString* StatutAssure;

	+ (CSCLoiMadelin*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
