/*
	CSCLiabilityRequest.h
	The implementation of properties and methods for the CSCLiabilityRequest object.
	Generated by SudzC.com
*/
#import "CSCLiabilityRequest.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCArrayOfLiabilityItem.h"
#import "CSCArrayOfString.h"
@implementation CSCLiabilityRequest
	@synthesize DisplayId = _DisplayId;
	@synthesize EffectiveDate = _EffectiveDate;
	@synthesize EndDate = _EndDate;
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize StartDate = _StartDate;
	@synthesize ItemList = _ItemList;
	@synthesize MedicalCodeList = _MedicalCodeList;
	@synthesize MedicalEndDate = _MedicalEndDate;
	@synthesize MedicalStartDate = _MedicalStartDate;

	- (id) init
	{
		if(self = [super init])
		{
			self.DisplayId = nil;
			self.EffectiveDate = nil;
			self.EndDate = nil;
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.StartDate = nil;
			self.ItemList = [[NSMutableArray alloc] init];
			self.MedicalCodeList = [[NSMutableArray alloc] init];
			self.MedicalEndDate = nil;
			self.MedicalStartDate = nil;

		}
		return self;
	}

	+ (CSCLiabilityRequest*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCLiabilityRequest*)[[CSCLiabilityRequest alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.DisplayId = [Soap getNodeValue: node withName: @"DisplayId"];
			self.EffectiveDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EffectiveDate"]];
			self.EndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EndDate"]];
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.StartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"StartDate"]];
			self.ItemList = [[CSCArrayOfLiabilityItem createWithNode: [Soap getNode: node withName: @"ItemList"]] object];
			self.MedicalCodeList = [[CSCArrayOfString createWithNode: [Soap getNode: node withName: @"MedicalCodeList"]] object];
			self.MedicalEndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"MedicalEndDate"]];
			self.MedicalStartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"MedicalStartDate"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"LiabilityRequest"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.DisplayId != nil) [s appendFormat: @"<DisplayId>%@</DisplayId>", [[self.DisplayId stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.EffectiveDate != nil) [s appendFormat: @"<EffectiveDate>%@</EffectiveDate>", [Soap getDateString: self.EffectiveDate]];
		if (self.EndDate != nil) [s appendFormat: @"<EndDate>%@</EndDate>", [Soap getDateString: self.EndDate]];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.StartDate != nil) [s appendFormat: @"<StartDate>%@</StartDate>", [Soap getDateString: self.StartDate]];
		if (self.ItemList != nil && self.ItemList.count > 0) {
			[s appendFormat: @"<ItemList>%@</ItemList>", [CSCArrayOfLiabilityItem serialize: self.ItemList]];
		} else {
			[s appendString: @"<ItemList/>"];
		}
		if (self.MedicalCodeList != nil && self.MedicalCodeList.count > 0) {
			[s appendFormat: @"<MedicalCodeList>%@</MedicalCodeList>", [CSCArrayOfString serialize: self.MedicalCodeList]];
		} else {
			[s appendString: @"<MedicalCodeList/>"];
		}
		if (self.MedicalEndDate != nil) [s appendFormat: @"<MedicalEndDate>%@</MedicalEndDate>", [Soap getDateString: self.MedicalEndDate]];
		if (self.MedicalStartDate != nil) [s appendFormat: @"<MedicalStartDate>%@</MedicalStartDate>", [Soap getDateString: self.MedicalStartDate]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCLiabilityRequest class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
