/*
	CSCMembership.h
	The interface definition of properties and methods for the CSCMembership object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCContract;
@class CSCArrayOfCoverageMembership;
@class CSCMembership;
@class CSCPerson;
@class CSCPerson;
#import "CSCObject.h"
@class CSCObject;


@interface CSCMembership : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	CSCContract* _Contract;
	NSMutableArray* _CoverageMembershipList;
	NSString* _Identifier;
	BOOL _Main;
	CSCMembership* _MainMembership;
	int _MaximumAge;
	CSCPerson* _Owner;
	CSCPerson* _Person;
	int _RiskCode;
	BOOL _Smoker;
	NSString* _Status;
	NSString* _StatusLabel;
	NSString* _Type;
	NSString* _TypeLabel;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) CSCContract* Contract;
	@property (strong, nonatomic) NSMutableArray* CoverageMembershipList;
	@property (strong, nonatomic) NSString* Identifier;
	@property BOOL Main;
	@property (strong, nonatomic) CSCMembership* MainMembership;
	@property int MaximumAge;
	@property (strong, nonatomic) CSCPerson* Owner;
	@property (strong, nonatomic) CSCPerson* Person;
	@property int RiskCode;
	@property BOOL Smoker;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSString* StatusLabel;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* TypeLabel;

	+ (CSCMembership*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
