/*
	CSCMedicalTreatment.h
	The implementation of properties and methods for the CSCMedicalTreatment object.
	Generated by SudzC.com
*/
#import "CSCMedicalTreatment.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
@implementation CSCMedicalTreatment
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize AgreementType = _AgreementType;
	@synthesize MedicalCodeDetail = _MedicalCodeDetail;
	@synthesize MedicalCodeName = _MedicalCodeName;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.AgreementType = nil;
			self.MedicalCodeDetail = nil;
			self.MedicalCodeName = nil;

		}
		return self;
	}

	+ (CSCMedicalTreatment*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCMedicalTreatment*)[[CSCMedicalTreatment alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.AgreementType = [Soap getNodeValue: node withName: @"AgreementType"];
			self.MedicalCodeDetail = [Soap getNodeValue: node withName: @"MedicalCodeDetail"];
			self.MedicalCodeName = [Soap getNodeValue: node withName: @"MedicalCodeName"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"MedicalTreatment"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.AgreementType != nil) [s appendFormat: @"<AgreementType>%@</AgreementType>", [[self.AgreementType stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MedicalCodeDetail != nil) [s appendFormat: @"<MedicalCodeDetail>%@</MedicalCodeDetail>", [[self.MedicalCodeDetail stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.MedicalCodeName != nil) [s appendFormat: @"<MedicalCodeName>%@</MedicalCodeName>", [[self.MedicalCodeName stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCMedicalTreatment class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
