/*
	CSCMedicalQuestionnaire.h
	The interface definition of properties and methods for the CSCMedicalQuestionnaire object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfQuestionAnswer;
#import "CSCObject.h"
@class CSCObject;


@interface CSCMedicalQuestionnaire : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	BOOL _AnswerSummary;
	NSString* _Identifier;
	NSMutableArray* _QuestionAnswerList;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property BOOL AnswerSummary;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) NSMutableArray* QuestionAnswerList;

	+ (CSCMedicalQuestionnaire*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
