/*
	CSCNetworkActivation.h
	The implementation of properties and methods for the CSCNetworkActivation object.
	Generated by SudzC.com
*/
#import "CSCNetworkActivation.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCHealthFormula.h"
@implementation CSCNetworkActivation
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize Formula = _Formula;
	@synthesize Insured = _Insured;
	@synthesize MemberCheck = _MemberCheck;
	@synthesize ThirdPartyPayer = _ThirdPartyPayer;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.Formula = nil; // [[CSCHealthFormula alloc] init];

		}
		return self;
	}

	+ (CSCNetworkActivation*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCNetworkActivation*)[[CSCNetworkActivation alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.Formula = [[CSCHealthFormula createWithNode: [Soap getNode: node withName: @"Formula"]] object];
			self.Insured = [[Soap getNodeValue: node withName: @"Insured"] boolValue];
			self.MemberCheck = [[Soap getNodeValue: node withName: @"MemberCheck"] boolValue];
			self.ThirdPartyPayer = [[Soap getNodeValue: node withName: @"ThirdPartyPayer"] boolValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"NetworkActivation"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.Formula != nil) [s appendString: [self.Formula serialize: @"Formula"]];
		[s appendFormat: @"<Insured>%@</Insured>", (self.Insured)?@"true":@"false"];
		[s appendFormat: @"<MemberCheck>%@</MemberCheck>", (self.MemberCheck)?@"true":@"false"];
		[s appendFormat: @"<ThirdPartyPayer>%@</ThirdPartyPayer>", (self.ThirdPartyPayer)?@"true":@"false"];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCNetworkActivation class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
