/*
	CSCNote.h
	The interface definition of properties and methods for the CSCNote object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCReference;
@class CSCArrayOfString;
@class CSCArrayOfString;
#import "CSCObject.h"
@class CSCObject;


@interface CSCNote : CSCObject
{
	NSString* _Accessibility;
	NSString* _AccessibilityLabel;
	NSString* _Author;
	CSCObject* _BusinessObject;
	NSDate* _CreationDate;
	CSCReference* _Object;
	NSMutableArray* _ProfileList;
	NSMutableArray* _Text;
	NSString* _Title;
	NSDate* _UpdateDate;
	
}
		
	@property (retain, nonatomic) NSString* Accessibility;
	@property (retain, nonatomic) NSString* AccessibilityLabel;
	@property (retain, nonatomic) NSString* Author;
	@property (retain, nonatomic) CSCObject* BusinessObject;
	@property (retain, nonatomic) NSDate* CreationDate;
	@property (retain, nonatomic) CSCReference* Object;
	@property (retain, nonatomic) NSMutableArray* ProfileList;
	@property (retain, nonatomic) NSMutableArray* Text;
	@property (retain, nonatomic) NSString* Title;
	@property (retain, nonatomic) NSDate* UpdateDate;

	+ (CSCNote*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
