/*
	CSCOrganizationProfile.h
	The interface definition of properties and methods for the CSCOrganizationProfile object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCOrganizationProfile : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDecimalNumber* _DomesticRate;
	int _ExecutivePayroll;
	int _HeadCount;
	NSString* _Imposition;
	NSDecimalNumber* _InternationalRate;
	NSDecimalNumber* _LumpSum;
	int _NonExecutivePayroll;
	NSDecimalNumber* _ProfitAmount;
	NSDecimalNumber* _TurnoverAmount;
	NSDecimalNumber* _TurnoverProgressionRate;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDecimalNumber* DomesticRate;
	@property int ExecutivePayroll;
	@property int HeadCount;
	@property (strong, nonatomic) NSString* Imposition;
	@property (strong, nonatomic) NSDecimalNumber* InternationalRate;
	@property (strong, nonatomic) NSDecimalNumber* LumpSum;
	@property int NonExecutivePayroll;
	@property (strong, nonatomic) NSDecimalNumber* ProfitAmount;
	@property (strong, nonatomic) NSDecimalNumber* TurnoverAmount;
	@property (strong, nonatomic) NSDecimalNumber* TurnoverProgressionRate;

	+ (CSCOrganizationProfile*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
