/*
	CSCObject.h
	The interface definition of properties and methods for the CSCObject object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface CSCObject : SoapObject
{
	
}
		

	+ (CSCObject*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
