/*
	CSCPenaltyRate.h
	The interface definition of properties and methods for the CSCPenaltyRate object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCOperation;
#import "CSCObject.h"
@class CSCObject;


@interface CSCPenaltyRate : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDecimalNumber* _OffPeriodRate;
	CSCOperation* _Operation;
	NSDecimalNumber* _Rate;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDecimalNumber* OffPeriodRate;
	@property (strong, nonatomic) CSCOperation* Operation;
	@property (strong, nonatomic) NSDecimalNumber* Rate;

	+ (CSCPenaltyRate*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
