/*
	CSCPeriod.h
	The interface definition of properties and methods for the CSCPeriod object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
#import "CSCObject.h"
@class CSCObject;


@interface CSCPeriod : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _EndDate;
	NSDate* _StartDate;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) NSDate* StartDate;

	+ (CSCPeriod*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
