/*
	CSCPenaltyRate.h
	The implementation of properties and methods for the CSCPenaltyRate object.
	Generated by SudzC.com
*/
#import "CSCPenaltyRate.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
#import "CSCOperation.h"
@implementation CSCPenaltyRate
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize OffPeriodRate = _OffPeriodRate;
	@synthesize Operation = _Operation;
	@synthesize Rate = _Rate;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.OffPeriodRate = nil;
			self.Operation = nil; // [[CSCOperation alloc] init];
			self.Rate = nil;

		}
		return self;
	}

	+ (CSCPenaltyRate*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCPenaltyRate*)[[CSCPenaltyRate alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.OffPeriodRate = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"OffPeriodRate"]];
			self.Operation = [[CSCOperation createWithNode: [Soap getNode: node withName: @"Operation"]] object];
			self.Rate = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"Rate"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"PenaltyRate"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.OffPeriodRate != nil) [s appendFormat: @"<OffPeriodRate>%@</OffPeriodRate>", [NSString stringWithFormat: @"%@", self.OffPeriodRate]];
		if (self.Operation != nil) [s appendString: [self.Operation serialize: @"Operation"]];
		if (self.Rate != nil) [s appendFormat: @"<Rate>%@</Rate>", [NSString stringWithFormat: @"%@", self.Rate]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCPenaltyRate class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
