/*
	CSCPayPoint.h
	The interface definition of properties and methods for the CSCPayPoint object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCOrganization;
@class CSCOrganization;
@class CSCOrganization;
@class CSCArrayOfEmployeeGroup;
@class CSCOrganization;
#import "CSCObject.h"
@class CSCObject;


@interface CSCPayPoint : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSString* _AdjusmentMode;
	CSCOrganization* _AdjustmentDeclarer;
	NSString* _AdjustmentMethod;
	NSString* _AdjustmentType;
	NSString* _BillReceiver;
	NSString* _CalculationMethod;
	NSString* _CalculationMode;
	NSString* _Channel;
	CSCOrganization* _Client;
	CSCOrganization* _Declarer;
	NSMutableArray* _EmployeeGroupList;
	NSString* _FrequencyType;
	NSString* _Identifier;
	NSString* _Label;
	CSCOrganization* _Payer;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSString* AdjusmentMode;
	@property (strong, nonatomic) CSCOrganization* AdjustmentDeclarer;
	@property (strong, nonatomic) NSString* AdjustmentMethod;
	@property (strong, nonatomic) NSString* AdjustmentType;
	@property (strong, nonatomic) NSString* BillReceiver;
	@property (strong, nonatomic) NSString* CalculationMethod;
	@property (strong, nonatomic) NSString* CalculationMode;
	@property (strong, nonatomic) NSString* Channel;
	@property (strong, nonatomic) CSCOrganization* Client;
	@property (strong, nonatomic) CSCOrganization* Declarer;
	@property (strong, nonatomic) NSMutableArray* EmployeeGroupList;
	@property (strong, nonatomic) NSString* FrequencyType;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) NSString* Label;
	@property (strong, nonatomic) CSCOrganization* Payer;

	+ (CSCPayPoint*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
