/*
	CSCPreference.h
	The implementation of properties and methods for the CSCPreference object.
	Generated by SudzC.com
*/
#import "CSCPreference.h"

#import "CSCObject.h"
#import "CSCArrayOfExtensionElement.h"
@implementation CSCPreference
	@synthesize Extension = _Extension;
	@synthesize ExtensionList = _ExtensionList;
	@synthesize ChannelCode = _ChannelCode;
	@synthesize ChannelLabel = _ChannelLabel;
	@synthesize ContactMotive = _ContactMotive;
	@synthesize ContactMotiveLabel = _ContactMotiveLabel;
	@synthesize EndDate = _EndDate;
	@synthesize StartDate = _StartDate;

	- (id) init
	{
		if(self = [super init])
		{
			self.Extension = nil; // [[CSCObject alloc] init];
			self.ExtensionList = [[NSMutableArray alloc] init];
			self.ChannelCode = nil;
			self.ChannelLabel = nil;
			self.ContactMotive = nil;
			self.ContactMotiveLabel = nil;
			self.EndDate = nil;
			self.StartDate = nil;

		}
		return self;
	}

	+ (CSCPreference*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (CSCPreference*)[[CSCPreference alloc] initWithNode: node];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.Extension = [[CSCObject createWithNode: [Soap getNode: node withName: @"Extension"]] object];
			self.ExtensionList = [[CSCArrayOfExtensionElement createWithNode: [Soap getNode: node withName: @"ExtensionList"]] object];
			self.ChannelCode = [Soap getNodeValue: node withName: @"ChannelCode"];
			self.ChannelLabel = [Soap getNodeValue: node withName: @"ChannelLabel"];
			self.ContactMotive = [Soap getNodeValue: node withName: @"ContactMotive"];
			self.ContactMotiveLabel = [Soap getNodeValue: node withName: @"ContactMotiveLabel"];
			self.EndDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"EndDate"]];
			self.StartDate = [Soap dateFromString: [Soap getNodeValue: node withName: @"StartDate"]];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Preference"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.Extension != nil) [s appendString: [self.Extension serialize: @"Extension"]];
		if (self.ExtensionList != nil && self.ExtensionList.count > 0) {
			[s appendFormat: @"<ExtensionList>%@</ExtensionList>", [CSCArrayOfExtensionElement serialize: self.ExtensionList]];
		} else {
			[s appendString: @"<ExtensionList/>"];
		}
		if (self.ChannelCode != nil) [s appendFormat: @"<ChannelCode>%@</ChannelCode>", [[self.ChannelCode stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.ChannelLabel != nil) [s appendFormat: @"<ChannelLabel>%@</ChannelLabel>", [[self.ChannelLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.ContactMotive != nil) [s appendFormat: @"<ContactMotive>%@</ContactMotive>", [[self.ContactMotive stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.ContactMotiveLabel != nil) [s appendFormat: @"<ContactMotiveLabel>%@</ContactMotiveLabel>", [[self.ContactMotiveLabel stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.EndDate != nil) [s appendFormat: @"<EndDate>%@</EndDate>", [Soap getDateString: self.EndDate]];
		if (self.StartDate != nil) [s appendFormat: @"<StartDate>%@</StartDate>", [Soap getDateString: self.StartDate]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[CSCPreference class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
