/*
	CSCQuestionAnswer.h
	The interface definition of properties and methods for the CSCQuestionAnswer object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfQuestionAnswer;
#import "CSCObject.h"
@class CSCObject;


@interface CSCQuestionAnswer : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	BOOL _AnswerBoolean;
	NSDate* _AnswerDate;
	int _AnswerInteger;
	NSDecimalNumber* _AnswerReal;
	NSString* _AnswerText;
	NSString* _AnswerType;
	NSMutableArray* _QuestionAnswerList;
	NSString* _QuestionIdentifier;
	int _QuestionNo;
	NSString* _QuestionText;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property BOOL AnswerBoolean;
	@property (strong, nonatomic) NSDate* AnswerDate;
	@property int AnswerInteger;
	@property (strong, nonatomic) NSDecimalNumber* AnswerReal;
	@property (strong, nonatomic) NSString* AnswerText;
	@property (strong, nonatomic) NSString* AnswerType;
	@property (strong, nonatomic) NSMutableArray* QuestionAnswerList;
	@property (strong, nonatomic) NSString* QuestionIdentifier;
	@property int QuestionNo;
	@property (strong, nonatomic) NSString* QuestionText;

	+ (CSCQuestionAnswer*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
