/*
	CSCRecourseRecovery.h
	The interface definition of properties and methods for the CSCRecourseRecovery object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCTechnicalOperation;
#import "CSCObject.h"
@class CSCObject;


@interface CSCRecourseRecovery : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	CSCTechnicalOperation* _TechnicalOperation;
	NSString* _Type;
	NSString* _TypeLabel;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) CSCTechnicalOperation* TechnicalOperation;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* TypeLabel;

	+ (CSCRecourseRecovery*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
