/*
	CSCSavingsFlow.h
	The interface definition of properties and methods for the CSCSavingsFlow object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCCoverageFund;
#import "CSCObject.h"
@class CSCObject;


@interface CSCSavingsFlow : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSDecimalNumber* _Amount;
	CSCCoverageFund* _CoverageFund;
	NSString* _DebitCredit;
	NSString* _FundIdentifier;
	NSDate* _FundValueDate;
	NSDate* _InvestmentDate;
	NSString* _Label;
	NSString* _Status;
	NSString* _Type;
	NSDecimalNumber* _UnitValue;
	NSDecimalNumber* _Units;
	NSDate* _ValueDate;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSDecimalNumber* Amount;
	@property (strong, nonatomic) CSCCoverageFund* CoverageFund;
	@property (strong, nonatomic) NSString* DebitCredit;
	@property (strong, nonatomic) NSString* FundIdentifier;
	@property (strong, nonatomic) NSDate* FundValueDate;
	@property (strong, nonatomic) NSDate* InvestmentDate;
	@property (strong, nonatomic) NSString* Label;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSDecimalNumber* UnitValue;
	@property (strong, nonatomic) NSDecimalNumber* Units;
	@property (strong, nonatomic) NSDate* ValueDate;

	+ (CSCSavingsFlow*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
