/*
	CSCSignedStatement.h
	The interface definition of properties and methods for the CSCSignedStatement object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfHealthItem;
#import "CSCObject.h"
@class CSCObject;


@interface CSCSignedStatement : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSMutableArray* _ItemList;
	NSDecimalNumber* _TotalAmount;
	NSDecimalNumber* _TotalNationalRefund;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSMutableArray* ItemList;
	@property (strong, nonatomic) NSDecimalNumber* TotalAmount;
	@property (strong, nonatomic) NSDecimalNumber* TotalNationalRefund;

	+ (CSCSignedStatement*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
