/*
	CSCSettlementPayment.h
	The interface definition of properties and methods for the CSCSettlementPayment object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCHealthBenefit;
@class CSCSettlementFolder;
@class CSCTechnicalOperation;
#import "CSCObject.h"
@class CSCObject;


@interface CSCSettlementPayment : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDecimalNumber* _DeductibleAmount;
	NSDate* _DisbursementDate;
	CSCHealthBenefit* _HealthBenefit;
	NSString* _PaymentType;
	CSCSettlementFolder* _SettlementFolder;
	NSString* _Status;
	NSString* _StatusMotive;
	NSString* _StatusMotiveLabel;
	CSCTechnicalOperation* _TechnicalOperation;
	NSString* _Type;
	NSString* _TypeLabel;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDecimalNumber* DeductibleAmount;
	@property (strong, nonatomic) NSDate* DisbursementDate;
	@property (strong, nonatomic) CSCHealthBenefit* HealthBenefit;
	@property (strong, nonatomic) NSString* PaymentType;
	@property (strong, nonatomic) CSCSettlementFolder* SettlementFolder;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSString* StatusMotive;
	@property (strong, nonatomic) NSString* StatusMotiveLabel;
	@property (strong, nonatomic) CSCTechnicalOperation* TechnicalOperation;
	@property (strong, nonatomic) NSString* Type;
	@property (strong, nonatomic) NSString* TypeLabel;

	+ (CSCSettlementPayment*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
