/*
	CSCSettlementTax.h
	The interface definition of properties and methods for the CSCSettlementTax object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCOrganization;
@class CSCPerson;
@class CSCOrganization;
@class CSCBankAccount;
@class CSCPostalAddress;
#import "CSCObject.h"
@class CSCObject;


@interface CSCSettlementTax : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDecimalNumber* _AmountAdjustment;
	NSDecimalNumber* _BasisAdjustment;
	NSString* _ExemptionMotive;
	NSString* _ExemptionMotiveLabel;
	NSDecimalNumber* _NetAmount;
	CSCOrganization* _Organization;
	CSCPerson* _Person;
	NSString* _Status;
	NSDate* _StatusDate;
	NSString* _StatusLabel;
	NSDecimalNumber* _TaxAmount;
	NSString* _TaxPaymentDelegation;
	NSDecimalNumber* _TaxRelief;
	NSDecimalNumber* _TaxRelief2;
	NSDecimalNumber* _TotalAbattement990I;
	NSDecimalNumber* _TotalMontantDelegue757B;
	NSDecimalNumber* _TotalPrimes757B;
	CSCOrganization* _Treasury;
	CSCBankAccount* _TreasuryBankAccount;
	NSString* _TreasuryPaymentType;
	CSCPostalAddress* _TreasuryPostalAddress;
	NSString* _Type;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDecimalNumber* AmountAdjustment;
	@property (strong, nonatomic) NSDecimalNumber* BasisAdjustment;
	@property (strong, nonatomic) NSString* ExemptionMotive;
	@property (strong, nonatomic) NSString* ExemptionMotiveLabel;
	@property (strong, nonatomic) NSDecimalNumber* NetAmount;
	@property (strong, nonatomic) CSCOrganization* Organization;
	@property (strong, nonatomic) CSCPerson* Person;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSDate* StatusDate;
	@property (strong, nonatomic) NSString* StatusLabel;
	@property (strong, nonatomic) NSDecimalNumber* TaxAmount;
	@property (strong, nonatomic) NSString* TaxPaymentDelegation;
	@property (strong, nonatomic) NSDecimalNumber* TaxRelief;
	@property (strong, nonatomic) NSDecimalNumber* TaxRelief2;
	@property (strong, nonatomic) NSDecimalNumber* TotalAbattement990I;
	@property (strong, nonatomic) NSDecimalNumber* TotalMontantDelegue757B;
	@property (strong, nonatomic) NSDecimalNumber* TotalPrimes757B;
	@property (strong, nonatomic) CSCOrganization* Treasury;
	@property (strong, nonatomic) CSCBankAccount* TreasuryBankAccount;
	@property (strong, nonatomic) NSString* TreasuryPaymentType;
	@property (strong, nonatomic) CSCPostalAddress* TreasuryPostalAddress;
	@property (strong, nonatomic) NSString* Type;

	+ (CSCSettlementTax*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
