/*
	CSCSwitch.h
	The interface definition of properties and methods for the CSCSwitch object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfCoverageFund;
#import "CSCObject.h"
@class CSCObject;


@interface CSCSwitch : CSCObject
{
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSMutableArray* _CoverageFundList;
	NSString* _Status;
	NSString* _Type;
	
}
		
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSMutableArray* CoverageFundList;
	@property (strong, nonatomic) NSString* Status;
	@property (strong, nonatomic) NSString* Type;

	+ (CSCSwitch*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
