/*
	CSCTaxSystem.h
	The interface definition of properties and methods for the CSCTaxSystem object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCObject;
@class CSCArrayOfExtensionElement;
@class CSCArrayOfDeathTax;
@class CSCLoiMadelin;
#import "CSCObject.h"
@class CSCObject;


@interface CSCTaxSystem : CSCObject
{
	NSString* _DisplayId;
	NSDate* _EffectiveDate;
	NSDate* _EndDate;
	CSCObject* _Extension;
	NSMutableArray* _ExtensionList;
	NSDate* _StartDate;
	NSMutableArray* _DeathTaxList;
	NSDecimalNumber* _FractionExoneree;
	NSDecimalNumber* _FractionImposee;
	NSString* _Identifier;
	CSCLoiMadelin* _LoiMadelin;
	NSString* _Option;
	NSString* _Residence;
	NSDecimalNumber* _TotalPrimesExonerees;
	NSDecimalNumber* _TotalPrimesImposees;
	NSDecimalNumber* _TotalRachatsExoneres;
	NSDecimalNumber* _TotalRachatsImposes;
	NSDecimalNumber* _TotalSocialContribution;
	
}
		
	@property (strong, nonatomic) NSString* DisplayId;
	@property (strong, nonatomic) NSDate* EffectiveDate;
	@property (strong, nonatomic) NSDate* EndDate;
	@property (strong, nonatomic) CSCObject* Extension;
	@property (strong, nonatomic) NSMutableArray* ExtensionList;
	@property (strong, nonatomic) NSDate* StartDate;
	@property (strong, nonatomic) NSMutableArray* DeathTaxList;
	@property (strong, nonatomic) NSDecimalNumber* FractionExoneree;
	@property (strong, nonatomic) NSDecimalNumber* FractionImposee;
	@property (strong, nonatomic) NSString* Identifier;
	@property (strong, nonatomic) CSCLoiMadelin* LoiMadelin;
	@property (strong, nonatomic) NSString* Option;
	@property (strong, nonatomic) NSString* Residence;
	@property (strong, nonatomic) NSDecimalNumber* TotalPrimesExonerees;
	@property (strong, nonatomic) NSDecimalNumber* TotalPrimesImposees;
	@property (strong, nonatomic) NSDecimalNumber* TotalRachatsExoneres;
	@property (strong, nonatomic) NSDecimalNumber* TotalRachatsImposes;
	@property (strong, nonatomic) NSDecimalNumber* TotalSocialContribution;

	+ (CSCTaxSystem*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
