/*
	CSCVariableDfn.h
	The interface definition of properties and methods for the CSCVariableDfn object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
#import "CSCObject.h"
@class CSCObject;


@interface CSCVariableDfn : CSCObject
{
	NSString* _Definition;
	NSString* _Name;
	NSString* _Type;
	
}
		
	@property (strong, nonatomic) NSString* Definition;
	@property (strong, nonatomic) NSString* Name;
	@property (strong, nonatomic) NSString* Type;

	+ (CSCVariableDfn*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
