/*
	CSCWMActivity.h
	The interface definition of properties and methods for the CSCWMActivity object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class CSCArrayOfString;
#import "CSCObject.h"
@class CSCObject;


@interface CSCWMActivity : CSCObject
{
	BOOL _Cancellation;
	NSDate* _EffectiveDate;
	NSString* _Identifier;
	NSString* _Key;
	NSString* _Label;
	int _No;
	NSDate* _RequestDate;
	NSString* _Status;
	NSString* _StatusLabel;
	NSString* _Type;
	NSDate* _UpdateDate;
	NSString* _User;
	NSMutableArray* _WorkqueueList;
	
}
		
	@property BOOL Cancellation;
	@property (retain, nonatomic) NSDate* EffectiveDate;
	@property (retain, nonatomic) NSString* Identifier;
	@property (retain, nonatomic) NSString* Key;
	@property (retain, nonatomic) NSString* Label;
	@property int No;
	@property (retain, nonatomic) NSDate* RequestDate;
	@property (retain, nonatomic) NSString* Status;
	@property (retain, nonatomic) NSString* StatusLabel;
	@property (retain, nonatomic) NSString* Type;
	@property (retain, nonatomic) NSDate* UpdateDate;
	@property (retain, nonatomic) NSString* User;
	@property (retain, nonatomic) NSMutableArray* WorkqueueList;

	+ (CSCWMActivity*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
